### ISSUE TITLE
ajax方式不支持本地加载

### ISSUE THREAD

**Issue by swit1983** [zhangxinxu/mobilebone#100]
我们利用的混合开发，用的cordova。html文件都在本地，但是mobilebone ajax 无法加载，能做兼容吗？

**Comment by zhangxinxu** [comment]
你好，这种需要客户端做中间件，一定的协议地址。

其实与mobilebone没有关系，你任何的直接Ajax都没法得到本地HTML文件。

**Comment by swit1983** [comment]
这个我搞错了，cordova本身是支持的
