### ISSUE TITLE
直接打开data-reload="root"当里面有自己的链接再点击会生成两个层

### ISSUE THREAD

**Issue by chfeizy** [zhangxinxu/mobilebone#104]
http://115.29.4.5/mobilebonetest/test/ajax-html/#&b.html
此为b页面，点击加载b页面
![image](https://cloud.githubusercontent.com/assets/6427629/7007904/63646342-dcc0-11e4-95eb-8cb305d56d06.png)

**Comment by zhangxinxu** [comment]
我刚看了下，并没有发现你说的现象~

**Comment by chfeizy** [comment]
http://115.29.4.5/mobilebonetest/test/ajax-html/#&b.html?uid=1
不好意思 是要带参数

**Comment by chfeizy** [comment]
Mobilebone.handleTapEvent

if ((attr_reload == null || attr_reload == "false") && store[clean_url]) {
这里加上root就可以了
if ((attr_reload == null || attr_reload == "false" || attr_reload == "root") && store[clean_url]) {

**Comment by chfeizy** [comment]
不对针对详细页这种再点回去没了 root 看来还得加判断处理

**Comment by zhangxinxu** [comment]
今天对data-reload重新设计了下，去除了attr_reload =  "root"这个鸡肋设计，看下还有没有类似问题。

**Comment by chfeizy** [comment]
可以了 直接 data-reload 就好
