### ISSUE TITLE
设置data-reload="root"出现重复载入page

### ISSUE THREAD

**Issue by xuetian120** [zhangxinxu/mobilebone#109]
具体操作，（默认页面中设置&lt;a href=&quot;detail.php?id=112&quot; data-reload=&quot;root&quot;&gt;XXXX&lt;/a&gt; 、&lt;a href=&quot;detail.php?id=113&quot; data-reload=&quot;root&quot;&gt;XXXX&lt;/a&gt;）
通过浏览器直接访问 http://localhost/#&amp;detail.php?id=112;
第一次载入&lt;div id=&quot;pageDetail&quot; class=&quot;page in&quot; data-title=&quot;被请求的HTML&quot; style=&quot;display: block;&quot;&gt;...&lt;/div&gt;
切换至页面首页，通过点击&lt;a href=&quot;detail.php?id=112&quot; rel=&quot;nofollow&quot;&gt;XXXX&lt;/a&gt;访问，会再次重复创建&lt;div id=&quot;pageDetail&quot; class=&quot;page in&quot; data-title=&quot;被请求的HTML&quot; style=&quot;display: block;&quot;&gt;...&lt;/div&gt;
此时设置的data-reload="root"，不能起作用。

**Comment by zhangxinxu** [comment]
你好，可以问下是那个版本吗？前几日push的v2.4.4（尚未release）就是主要修复你说的的这个问题的~
