### ISSUE TITLE
如何完美支持前台根据后台接口呈现页面的方式？

### ISSUE THREAD

**Issue by xuetian120** [zhangxinxu/mobilebone#110]
如何方便处理接口方式开发，后台提供不同数据接口，前台对应一个页面，里面通过接口调用数据做最后展示，如果用Mobilebone.jsonHandle显然是不合适的，如果用<a href="detail.html?id=1">查看详情</a>，怎么实现根据id=1请求接口数据，最后渲染呈现test.html完整页面！
文件结构：detail.html含部分静态结构 + 接口获取动态数据 == 页面输出
你的说法：
页面骨架，也就是page主体，也就是一个空div默认就载入，然后所有的切换都是基本切换，而不是Ajax切换。在切换即将开始的时候（回调），您就可以使用自己，例如Zepto的Ajax方法去请求你需要的JSON数据，做你任何想做的事情，完全没有Mobilebone的限制。
问题来了，浏览器刷新怎么处理，没法支持刷新！

**Comment by zhangxinxu** [comment]
1. 你请求的JSON数据可携带区分页面的id或其他标志量，然后可以根据其寻找对应的模板内容进行渲染。
2. 浏览器刷新依然是正常显示。

**Comment by xuetian120** [comment]
理解有误，通常来说如果不借用Mobilebone做单页面切换，而直接通过url访问一个页面地址，该页面基本可以是一个静态页面，主要作为结构布局，外加一些静态内容，同时会有几个（多个）不同ajax请求数据，分别渲染填充进页面结构中。如果用Mobilebone.jsonHandle显然是不合适的，第一只接受一个json；第二Mobilebone.jsonHandle作为一个全局方法，不方便区分，必须后台对数据输出做区分，很局限。

就目前来说前端跟后端协作，习惯通过json做对接，一个页面由多个json接口返回数据再生成页面很常见，如何满足这类？你说的JSON数据可携带区分页面的id，只能满足单接口请求，如果设置了Mobilebone.captureLink = false;，跳出刷新页面的话，就是一个接口请求，显然是不能同时满足的！

**Comment by zhangxinxu** [comment]
如果你有这样的需求，JSON部分可以使用传统方式实现，Mobilebone由于规则设计简单，完全不影响使用的。你可以在过场执行之前做处理，也可以在过场之后。

**Comment by xuetian120** [comment]
通过事件是可以处理数据请求，但是这么干往往兼顾不到url的刷新，如何又可以直接通过浏览器地址来访问到？

**Comment by zhangxinxu** [comment]
可以的，url刷新会触发多个回调。你之前过场时候回调是怎么初始化的，刷新的时候也会初始化。
