### ISSUE TITLE
有关ajax处理

### ISSUE THREAD

**Issue by Athlen** [zhangxinxu/mobilebone#112]
张先生：
你好！看了有关mobilebone的介绍，觉得真心不错，并想引入到我们的项目中。但现在有个问题想请教一下。
我的一个页面是一个form，提交后，只返回处理结果true或false。而处理成功和处理失败的结果提示都已写在此页面的其他page里。
我查看了有关ajax请求的demo，是返回html代码作为请求成功后的新page。
但我不想把html内容写在php的echo中。这个怎么处理？

**Comment by xuwei0930** [comment]
返回true再回调函数里面写相应的html内容就可以了把

**Comment by zhangxinxu** [comment]
你好，此时<code>form</code>添加<code>data-ajax="false"</code>, 或者全局设置<code>Mobilebone.captureForm = false; </code> 然后你按照传统方式处理你的<code>form</code>表单提交。
