### ISSUE TITLE
Mobilebone如何处理一个页面对应对个接口请求的切换并支持浏览器地址刷新？

### ISSUE THREAD

**Issue by diandian123** [zhangxinxu/mobilebone#113]
平时开发页面，通常在一个页面内部对应发起多个接口请求，根据不同接口返回数据再组装相应dom，最后进行页面回填！

直接问题在于借用Mobilebone ajax请求的页面，不能执行页面里面的接口请求，意味着页面中做不了任何事情，只是一个固定抛出的html。

对于一个页面，多个接口，Mobilebone如何做加载，如果只是把页面加载回来，里面的那些接口请求怎么办？虽说可以在Mobilebone的回调中再做接口请求处理，但是如果要同时兼顾到url刷新，要知道接口通常不是死的，也会需要接受一定参数，什么方式处理最优，会有很多挖掘的问题，真正项目中推广使用起来目前还是有很多局限性！

**Comment by xuetian120** [comment]
有必要支持ajax请求页面内部的脚本执行，不太建议都要在全局回调中再处理脚本，不利于管理，页面一多会导致加载做回调处理的脚本很大！
