### ISSUE TITLE
mobilebone固定头尾布局，中间区域有input输入时候，软键盘的出现导致当前看不到input

### ISSUE THREAD

**Issue by xuetian120** [zhangxinxu/mobilebone#114]
问题描述：对头固定头与底，中间区域可滚动的布局，如果中间区域有input录入值，此时调出手机的软键盘，内容往上移，这时候input输入框就不在当前可见视窗。
&lt;div class=&quot;page out&quot;&gt;
	&lt;div class=&quot;header&quot; data-role=&quot;header&quot;&gt;
    	&lt;a href=&quot;javascript:&quot; class=&quot;icon-back&quot; data-rel=&quot;back&quot;&gt;返回&lt;/a&gt;
        &lt;h1&gt;固定头部&lt;/h1&gt;
    &lt;/div&gt;
	&lt;div class=&quot;content&quot;&gt;
    	&lt;div class=&quot;product-detail&quot;&gt;
        	&lt;div style=&quot;height:1000px; background:#6FF;&quot;&gt;中间内容高度&lt;/div&gt;
            &lt;div&gt;输入数量：&lt;input type=&quot;number&quot; placeholder=&quot;数量&quot;&gt;&lt;/div&gt;
    	&lt;/div&gt;
   	&lt;/div&gt;
	&lt;div class=&quot;footer&quot; data-role=&quot;header&quot;&gt;
		&lt;span&gt;固定底部&lt;/span&gt;
    &lt;/div&gt;
&lt;/div&gt;

问题：就是当我滚动中间区域到输入数量时，手机出现软键盘，这时候就看不到input了，需要在中间区域向下滚动才出现。有什么办法可以出现软键盘，当前视窗就定位在input 输入。

**Comment by chfeizy** [comment]
是不是用的 搜狗输入法
iphone自带的是可以自动推上来的

**Comment by xuetian120** [comment]
是的，安卓系统中不行。
