### ISSUE TITLE
点击比较快转场很容易就出问题

### ISSUE THREAD

**Issue by chfeizy** [zhangxinxu/mobilebone#117]
这个 很频繁呢 点快点的话 直接 #pageHome 锚点页
还是iphone的safari ios8.1.2

**Comment by zhangxinxu** [comment]
你好，有可访问的地址吗？我看下~

**Comment by chfeizy** [comment]
http://www.v-town.cc/
点导航的 首页 发现 微店 快速点击
现在chrome测试也会有问题

**Comment by chfeizy** [comment]
http://www.v-town.cc/
点导航的 首页 发现 微店 快速点击
现在chrome测试也会有问题

**Comment by chfeizy** [comment]
还有个问题
data-callback直接#&test.html?id=111打开不执行
从别的页面进入才执行

**Comment by xuetian120** [comment]
这是因为你的参数是通过事件传递的，直接url肯定访问不执行！

**Comment by xuetian120** [comment]
mobilebone的设置会导致过多的依赖回调，因为ajax请求页面本身不能执行内部的脚本。

**Comment by chfeizy** [comment]
好像新的 evlscript 可以了 还没尝试
data-callback 也算内部了 不是加载后回调吗

**Comment by zhangxinxu** [comment]
你的问题是指不连续吗？
我本地测试了一下，直接打开是会执行data-callback的，可否提供有问题的Demo页面。

**Comment by xuetian120** [comment]
在于url参数上，如果是事件传递的参数就是他说的刷新不行！

**Comment by chfeizy** [comment]
不是参数在url 上的问题
我说的 是直接打开页面 data-callback 没执行
有的时候用户直接在当前页面刷新或者把页面分享出去了

**Comment by chfeizy** [comment]
那有可能是 seajs 的问题 我现在都是把window.loadmsg = exports.loadmsg;
不知道是不是执行顺序的问题我改到开始的 app.js里试试

**Comment by chfeizy** [comment]
刚测试了直接打开data-callback 执行了，这个没问题了
转场的问题呢?

**Comment by chfeizy** [comment]
还是直接打开的问题
第一次打开，点后退就没有历史记录了，后退不了
可否配置一个默认跳转地址或者首页，没记录点后退就去首页，或者更灵活点直接 后退按钮上也支持 data-backurl 之类的配置，有时候后退想去上一级不一定就是历史

**Comment by zhangxinxu** [comment]
@chfeizy 关键没法知道用户是前进还是后退，只知道总共的历史记录长度，不知道当前的位置。

**Comment by xuetian120** [comment]
测试同学发现，安卓机器快速的点击操作，会出现空白页面！

**Comment by chfeizy** [comment]
@zhangxinxu 项目地址给你发腾讯微薄了，有注意到没，账号密码也有发的
