### ISSUE TITLE
单独排除某a元素的过场效果

### ISSUE THREAD

**Issue by Athlen** [zhangxinxu/mobilebone#119]
有没有在保留全局链接的过场效果(Mobilebone.captureLink =true)情况下，只排除某些a元素的过场效果。比如在a元素的可设置什么属性令此a元素的过场效果失效。
---------运用场景----------
bootstrap挺不错，省去了我们自己定义样式和某些JS的麻烦，但由于bootstrap的使用有较强的结构性，在结合Mobilebone后有可能对各自的JS效果都有影响。
如bootstrap中的标签页中也有a元素，此时我想使用bootstrap的标签页切换的效果，但由于本页中有其他使用Mobilebone的地方，而Mobilebone的全局链接都有过场效果，导致bootstrap的标签页切换显示有问题。

bootstrap参考链接：http://v3.bootcss.com/components/#nav-tabs

**Comment by zhangxinxu** [comment]
有的。data-rel="external"

**Comment by Athlen** [comment]
这里提议一下，每个元素可设置什么属性各做一个demo出来，让菜鸟们可以直观看到效果。
可以的话，可引入一些编辑即显示之类的页面，可以让我们在上面修改一下参数来马上看到效果，这对学习和使用mobileBone很有好处。
如：http://www.w3cschool.cc/try/try.php?filename=tryjs_events

**Comment by dancinglone** [comment]
对对对，如果鑫哥有时间做出这样的demo，对广大前端小白来说就是福音啦。

**Comment by zhangxinxu** [comment]
@Athlen 好的，我会陆续集成到API文档页面中……
