### ISSUE TITLE
安卓4.0以下不支持history api的浏览器，用history.js能兼容吗？

### ISSUE THREAD

**Issue by zdfsilence** [zhangxinxu/mobilebone#120]
如题，本来以为4.0以上的都支持的，结果发现4.0.3的安卓不支持history api。而我们这要求兼容到4.0

**Comment by zdfsilence** [comment]
找到问题了，低版本安卓不是不支持history api，是不支持classList属性，而且xhr的response属性要改成responseText属性

**Comment by zdfsilence** [comment]
看来是我太年轻了，现在经过我们这用户反馈的排查结果来看，安卓主要的问题是 2,3.x的系统支持history api但不支持classList和xhr.response， 但是安卓4.0.3 4.0.4这两个奇葩版本是不支持history api。我顺便也反馈一下作者，希望能有优化吧

**Comment by zdfsilence** [comment]
问题已解决。

用location.hash替代history.pushstate, location.replace替代history.replacestate
hashchange事件替代popstate事件

**Comment by zhangxinxu** [comment]
好，顶，赞！
