### ISSUE TITLE
页面切换后Javascritp不能执行！

### ISSUE THREAD

**Issue by yuefengkai** [zhangxinxu/mobilebone#121]
Main页面
A页面

 从Main页面点击链接到A后 A页面的Javascript不能执行  A的Js在Main里也有

**Comment by dancinglone** [comment]
不可能啊。发个链接看看？

**Comment by yuefengkai** [comment]
http://gaozengzhi.cn/testajax/index.html

demo在这里   我把create.innerHTML = domHtml; 改成 //$(create).html(domHtml); 可以执行所有页面的js

但是我现在遇到了另一切换的问题   就是demo里的 基本slide切换效果  
从Main页面到A页面用ajax   在A页面里有几个基本切换  点击没反应

**Comment by dancinglone** [comment]
你把js写在ajax加载的页面里是不会加载的吧？加载的只是body里的标签而已。

**Comment by zhangxinxu** [comment]
你好，新增的Mobilebone.evalScript可以执行加载的HTML内容中的JS内容，默认是false不执行。以url地址形式连接的script文件是不会执行的。
原因在于：
Mobilebone设计的初衷是这样的：Main页面就是我们平常的main页面，就算没有Mobilebone也可以正常访问，A页面单独访问也是一个正常的页面。加上了Mobilebone，就变成滑来滑去效果。因此，几乎跟传统开发无异。显然，Main页面和A页面会有一些同样的JS文件，例如jQuery或common.js之类。显然，在Mobilebone看来头部或尾部的JS文件是万万不能重复执行的。

**Comment by dancinglone** [comment]
点赞，这个新增的方法还是比较实用的！
