### ISSUE TITLE
Ajax切换加基本切换无效

### ISSUE THREAD

**Issue by yuefengkai** [zhangxinxu/mobilebone#122]
Main页面
A页面

从Main点击到A页面用 Ajax切换
A页面里有几个page需要基本切换 
点击A页面的基本切换没有反应

将测试demo的Mobilebone.captureLink = false;  该为true后 基本切换也是无效的

**Comment by zhangxinxu** [comment]
你好，页面内切换，需要用到data-container~

**Comment by yuefengkai** [comment]
你好，按你说的加data-container 无效

是从ajax过度到A 在A里面做基本切换

**Comment by yuefengkai** [comment]
我又试了一下 是不行的   
如果单独打开A 是可以切换的   
只要从Main页面Ajax过来到A然后点击A里面的基本切换就没反应了

**Comment by zhangxinxu** [comment]
切换是全局委托的。第一次有这样的反馈，有Demo页面让我瞅瞅吗？

**Comment by yuefengkai** [comment]
demo我发你邮箱了


http://gaozengzhi.cn/testajax/index.html


这个地方也有 基本切换的那个
在2015年04月26日 00:11，zhangxinxu 写道:

切换是全局委托的。第一次有这样的反馈，有Demo页面让我瞅瞅吗？

**Comment by zhangxinxu** [comment]
看看这个 示例 是不是你想要的 http://rawgit.com/zhangxinxu/mobilebone/develop/docs/index.html#&data-classPage.html

**Comment by yuefengkai** [comment]
你好！ 我试过这个只要和ajax结合到一起就不起作用了

**Comment by zhangxinxu** [comment]
@yuefengkai v2.6.0局部切换也支持Ajax切换效果了。
