### ISSUE TITLE
与腾讯出品的frozenjs不兼容，移动状态下所有的a,button等都失效，不能响应事件

### ISSUE THREAD

**Issue by julor** [zhangxinxu/mobilebone#123]
frozenjs项目地址：https://github.com/frozenui/frozenjs
只在，Mobilebone.captureLink = false时，才能响应事件。我要怎么那修改？

**Comment by julor** [comment]
经过测试，在pc模式下可以mobilebone有效，如果切换到移动状态下就无效了，我输出tap,click事件，可以看到正常输出，但是mobilebone不能正常工作。最奇怪的是，我加入监控tap,click事件后，pc模式又不能工作了，只能移动模式下才行。
$('a').tap(function () {
            console.info('tap')
        })
        $('a').click(function () {
            console.info('click')
        })
已经测试吧，两款手机，和一个平板均出现以上描述的问题，求解决！

**Comment by zhangxinxu** [comment]
v2.5.1+ 已更新

**Comment by julor** [comment]
支持一个，非常感谢

**Comment by julor** [comment]
还存在兼容性问题，上个版本是ajax之前内容不能响应，但是之后的a链接没问题，现在的版本修复了ajax之前的链接不能响应问题，但是ajax新内容中所有的<a>不响应，无论pc或者mobile

**Comment by julor** [comment]
加入frozenjs后，我看到输出的log由MouseEvent，变成Event

**Comment by zhangxinxu** [comment]
好的，感谢反馈，晚上看下~

**Comment by zhangxinxu** [comment]
你好，我测试了下，无此问题，可否提供可访问Demo？

**Comment by zhangxinxu** [comment]
据我反复测试，是frozenjs自身的问题。为了所谓的点透问题(http://frozenui.github.io/frozenjs/basic/tap/index.html)，自以为是阻止了所以绑定了tap事件元素的默认行为。因此，普通的链接也不能跳转了。 因此，你可能需要额外处理。

**Comment by julor** [comment]
感谢这么晚了，还在为我调试代码。
按frozenjs上面说的zepto的点击tap存在问题。
mobilebone没有处理ajax进来新页面中所有的tap事件，这个问题和mobilebone2.5.0正好相反，当时是之处理ajax后的页面。

$("#link").on("tap", function() {
   console.info(this.href);
    location.href = this.href;  
});
这段代码无效，如果是基本转场2.5.1现在与frozenjs没有兼容性问题。

若是ajax进来的页面，tap事件没有响应，以上的console没有输出。

我想，如果2.5.0与2.5.1中处理tap事件的能力结合起来，就不会存在兼容性问题了。

**Comment by zhangxinxu** [comment]
你好，不知你是怎么测试的。

我测试的现象是这样的：
1. 就算没有Mobilebone.js, 任何链接，只要绑定了frozenjs的tap事件，原来的链接跳转效果都会消失（也就是阻止了click的默认行为）。可能在frozenjs看来，移动端的任何click行为都是多余的。

2. Mobilebone 2.5.1和2.5.0的区别在于，2.5.0使用的是<code>document.addEventListener("tap")</code>去做全局委托，可惜像frozenjs这样的业余事件处理对此不支持（Zepto的touch支持的）；于是，2.5.1版本使用的是，<code>$(document).on("tap")</code>，使用了Zepto风格的事件绑定。这种用法frozenjs是支持的。从作用上讲，完全没有任何区别。

3. 没有所谓的Ajax前与Ajax之后，因为所有&lt;a&gt;元素的点击都是走的全局委托。为何你会这么误解，我猜想你的页面正好Ajax之后有个&lt;a&gt;链接。其实这个&lt;a&gt;链接在页面之前，也是不能正常跳转的。

4. $("#link")元素是Ajax载入的，你是Ajax之前绑定，自然不会有响应的，例如写在data-onpagefirstinto回调中，你就会看到正常跳转了！

5. 我的建议是，不要使用frozenjs的touch，试试千锤百炼的Zepto的touch~

**Comment by julor** [comment]
http://opengiser.qiniudn.com/mobilebone.zip

以上是我在chrome开启**toggle device mode**时，测试代码，实际与手机体验一致。
分三种，
第一不加moblebone，所有的buttong ,a在pc和mobile模式均有效。
第二第三分别使用mobilebone2.5.0及2.5.1测试.2.5.0，两个版本的mobilebone结果正好相反。

**Comment by julor** [comment]
求作者解决

**Comment by julor** [comment]
求解决

**Comment by zhangxinxu** [comment]
frozenjs中任何a元素绑定了tap方法，就会干掉原来的click行为，例如链接跳转；想zepto.js等tap事件处理都不会这么自以为是的。

Mobilebone为了实时捕获每个a元素是否需要过场，因此，利用已有的tap方法做了全局委托：$(document).tap(this.handleTapEvent);

跟frozenjs搞在一起，就会导致所有的a元素都tap化。

Mobilebone此时有些无能为力。

你可以，在外部，对需要处理的a元素辅助tap事件，实现其默认行为，例如：
<pre>$("#link").on("tap", function() {
    location.href = this.href;
});</pre>

或者，你修改Mobilebone：
<pre>$(document).tap(this.handleTapEvent); →  $(document).click(this.handleTapEvent);</pre>

**Comment by zhangxinxu** [comment]
我在Mobilebone内部手动location.href了外链地址，v2.6.1~~

**Comment by julor** [comment]
非常感谢这么晚了还在帮我们改bug，刚才测试了下问题还是有，我去掉了frozen.js的tap插件了，用faskclick代替，现在完美。
