### ISSUE TITLE
点击事件不起效链接无效

### ISSUE THREAD

**Issue by zhongjq** [zhangxinxu/mobilebone#124]
https://github.com/BR0kEN-/jTap 我的页面使用了这个库，mobilebone的tap事件不起效，所以切换不了，不用这个库就可以运行

**Comment by julor** [comment]
和我刚才的那个问题有点类似，我是用了腾讯的frozenjs，在pc模式下可以mobilebone有效，如果切换到移动状态下就无效了，我输出tap,click事件，可以看到正常输出，但是mobilebone不能正常工作。最奇怪的是，我加入监控tap,click事件后，pc模式又不能工作了，只能移动模式下才行。
$('a').tap(function () {
            console.info('tap')
        })
        $('a').click(function () {
            console.info('click')
        })
已经测试吧，两款手机，和一个平板均出现以上描述的问题，求解决！

**Comment by zhangxinxu** [comment]
好的，收到反馈~

**Comment by zhangxinxu** [comment]
v2.5.1+ 已更新

**Comment by zhongjq** [comment]
3q
