### ISSUE TITLE
直接输入地址访问时，title小问题

### ISSUE THREAD

**Issue by julor** [zhangxinxu/mobilebone#127]
可以用完整页面的title或者data-title属性作为整个文档的标题，但是如果不是按整个流程点下去用ajax获取内容，而是直接输入地址，此时title如何更好处理？

**Comment by zhangxinxu** [comment]
我没脑补出有什么区别，可否举个例子？

**Comment by julor** [comment]
通过上一页面进入：
http://niu.bi/xxx#&xxx，只返回干净的页面，此时有title我是牛逼网
如果直接输入以上网址，由于没有通过data-title传值，此时没有title显示了。
如果返回的是局部页面，不通过data-title传值，那怎么显示title呢？

**Comment by zhangxinxu** [comment]
局部页面的&lt;div class="page"> 设置data-title就可以了~ 如&lt;div class="page" data-ttile="标题，哈哈~">

**Comment by zhangxinxu** [comment]
文档有说明：http://rawgit.com/zhangxinxu/mobilebone/develop/docs/index.html#&data-title.html

**Comment by julor** [comment]
非常感谢，我理解错了。
