### ISSUE TITLE
改了点东西，不知道算不算优化

### ISSUE THREAD

**Issue by yuefengkai** [zhangxinxu/mobilebone#128]
168行  back = options.target != undefined && options.target.getAttribute("data-rel") == "back"; 

起因
所有的进入切换都是从右往左切换，
所有的后退应该都从左往右
但是当页面刷新后再次点击后退时切换效果是从右往左切换的  （PS：可能我是个例，返回用的ajax data-reload）
所以
一步步调试到168行 将back 参数默认为false   通过判断target 自定义属性，如果是back就设置为true，切换就变成从左往右了。

求张老师为我解惑ajax切换+基本切换。。。。 #122 号问题

**Comment by zhangxinxu** [comment]
好的，感谢反馈，我有时间评估下。

**Comment by zhangxinxu** [comment]
感谢反馈，Ajax的back处理确实有问题~
