### ISSUE TITLE
form在post之后的过场疑惑

### ISSUE THREAD

**Issue by Athlen** [zhangxinxu/mobilebone#132]
现在使用mobilebone的情况下，在form在post之后，是变成异步提交了，而过场后的page的内容则是post处理后返回的reponse中取得的内容。
但由于现在我需要的情景是，post之后返回true或false来对应这个form提交后的结果，
这里是否可以在html中已写好提交成功和提交失败的过场page，然后form中加上success-to-page和fail-to-page之类的属性的page值来分别对应提交成功和提交失败的过场page？

**Comment by zhangxinxu** [comment]
你好，这个交给使用者控制比较好，过于复杂的规则，反而限制了事物的潜力。两种处理方法：
1. form data-aajx="false" 自己处理Ajax请求，再回调中使用Mobilebone.transition过场页面~
2. 设置form  data-datatype="json", 然后在Mobilebone.jsonHandle中根据true, flase使用Mobilebone.transition过场对应的页面。

**Comment by Athlen** [comment]
好的，感觉第一个方案会简单点。谢谢！
