### ISSUE TITLE
请教，我的loading是一个方法，能否调用呢？

### ISSUE THREAD

**Issue by hackchen** [zhangxinxu/mobilebone#133]
请教，我的loading是一个方法，能否调用呢？
比如我的loading是showLoading 是显示，hideLoading是关闭

**Comment by zhangxinxu** [comment]
你好，你可以修改CSS文件成你的loading样式效果。目前没法使用外部方法，因为不仅仅是个loading效果，还有一些判断在里面。

**Comment by zhangxinxu** [comment]
Mabolebone.showLoading = 你的loading显示方法名称。
Mabolebone.hideLoading = 你的loading隐藏方法名称。
