### ISSUE TITLE
b页面到c页面，c页面到d，如此深度进去再点击浏览器后退报错

### ISSUE THREAD

**Issue by xuetian120** [zhangxinxu/mobilebone#135]
最新版本点击浏览器后退报错;
<a href="classify.html?id=1" data-reload="">11122</a>
顺序从classify.html?id=1到classify.html?id=2到classify.html?id=3到classify.html?id=4

此时点击浏览器后退报错如下；
Uncaught TypeError: Cannot read property 'compareDocumentPosition' of undefined

**Comment by xuetian120** [comment]
举个例子：多级分类
在mobilebone-master\test\ajax-html下的index.html加入
&lt;li&gt;&lt;a href=&quot;category.php?id=1&quot;&gt;当前是一级分类&lt;/a&gt;&lt;/li&gt;
新建category.php内容为：
&lt;html&gt;
&lt;head&gt;
&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
&lt;/head&gt;
&lt;body&gt;
&lt;div class=&quot;page out&quot;  id=&quot;Category&quot;&gt;
	&lt;ul&gt;
&lt;?php
	if($_GET[&#x27;id&#x27;] == &#x27;1&#x27;) {
		echo &#x27;&lt;li&gt;&lt;a href=&quot;category.php?id=11&quot;&gt;当前是二级分类&lt;/a&gt;&lt;/li&gt;&#x27;;
	} elseif ($_GET[&#x27;id&#x27;] == &#x27;11&#x27;) {
		echo &#x27;&lt;li&gt;&lt;a href=&quot;category.php?id=111&quot;&gt;当前是三级分类&lt;/a&gt;&lt;/li&gt;&#x27;;
	} elseif ($_GET[&#x27;id&#x27;] == &#x27;111&#x27;) {
		echo &#x27;&lt;li&gt;&lt;a href=&quot;category.php?id=1111&quot;&gt;当前是四级分类&lt;/a&gt;&lt;/li&gt;&#x27;;
	} else {
		echo &#x27;&lt;li&gt;没有下级分类了&lt;/li&gt;&#x27;;
	}
?&gt;
	&lt;/ul&gt;
&lt;/div&gt;
&lt;/body&gt;
&lt;/html&gt;
此时点击index.html里面的&lt;li&gt;&lt;a href=&quot;category.php?id=1&quot;&gt;当前是一级分类&lt;/a&gt;&lt;/li&gt;进入到#&category.php?id=1，继续点击进入#&category.php?id=11，继续点击进入#&category.php?id=111最后到#&category.php?id=1111，&lt;strong style=&quot;color:#f00&quot;&gt;问题来了，此时点击浏览器后退页面出现空白！&lt;/strong&gt;

如果添加&lt;strong style=&quot;color:#f00&quot;&gt;data-reload&lt;/strong&gt;，例如&lt;li&gt;&lt;a href=&quot;category.php?id=1&quot; data-reload&gt;当前是一级分类&lt;/a&gt;&lt;/li&gt; （echo &#x27;&lt;li&gt;&lt;a href=&quot;category.php?id=11&quot; data-reload&gt;当前是二级分类&lt;/a&gt;&lt;/li&gt;&#x27;)
会报错&lt;strong style=&quot;color:#f00&quot;&gt;“Uncaught TypeError: Cannot read property 'compareDocumentPosition' of undefined”&lt;/strong&gt;

可能原因在同一page中做多级分类时出现pageinto、pageout是同一个，导致浏览器后退问题报错，希望解决！

**Comment by xuetian120** [comment]
事实上从一个url链接进入一个页面，该页面如果含有与上一个链接一样的url，只是url后面跟的参数不一样，都会存在浏览器后退问题！

**Comment by zhangxinxu** [comment]
好的，非常感谢反馈~

**Comment by zhangxinxu** [comment]
先更新了，今天时间太晚，我明后再看看，有些地方可能需要重新设计~

**Comment by xuetian120** [comment]
补充：测试发现对于test.php?id=1后面参数的变化（id=2、id=3、id=4...），此种情况会在同一div的page中变化内容，mobilebone没有对打开的地址记录进history，导致浏览器后退经常会空取不到值，必须按下回车刷新才显示正确的内容！

**Comment by xuetian120** [comment]
经测试，还是满足不了做多级分类场景时，下级页面与上级页面打开的都是同一页面，仅仅参数变化的情况！

**Comment by xuetian120** [comment]
深入进去几级分类后，点击浏览器后退页面一片空白！

**Comment by xuetian120** [comment]
在子级分类后退操作时，跟踪发现了二个同样的page结构，一个隐藏，一个显示，但是隐藏的为后退时应该显示的内容，当前显示的却是一个空内容页。

**Comment by xuetian120** [comment]
测试例子中test/ajax-html，点击打开index.html里面大多链接后，再进行浏览器后退查看操作发现index.html出现很多个重复div page出现！

**Comment by xuetian120** [comment]
测试例子中test/ajax-html，点击打开index.html里面大多链接后，再进行浏览器后退查看操作发现index.html出现很多个重复div page出现！
结构都为：
&lt;div class=&quot;page slide reverse out&quot; data-callback=&quot;optionsTest&quot; data-onpagefirstinto=&quot;init&quot; data-title=&quot;被请求的HTML&quot; style=&quot;display: block;&quot;&gt;
	&lt;a href=&quot;#pageHome&quot; data-rel=&quot;back&quot;&gt;返回&lt;/a&gt;
    &lt;button class=&quot;ajaxButton&quot;&gt;点击我&lt;/button&gt;
    &lt;p class=&quot;result&quot;&gt;inited! &lt;/p&gt;
    &lt;script&gt;
		console.log(&quot;loaded: &quot; + Date.now());
	&lt;/script&gt;
&lt;/div&gt;

**Comment by xuetian120** [comment]
比如先打开test/ajax-html/index.html页面前面6个页面，再点击浏览器后退，查看dom结构就会发现没后退一下就生成一个新的div结构块！（注意只操作一个链接的前进与后退还不好观察到问题）

**Comment by xuetian120** [comment]
为什么点浏览器后退的时候都不会刷新重载页面区域内容，这样设计不太合理！

**Comment by xuetian120** [comment]
目前mobilebone的前进、后退，对应的历史记录始终感觉漂浮一定，多操作一下，就找不到规律，跟浏览器的历史记录不同，这个最好保持一致！

浏览器后退直接从内存中读取内容，这对于动态页面、或者实时性稍微强一点的应用都不可取。直接说mobilebone更适合于显示静态不变更的页面，或者后台稳定输出html内容，对于前端解析json动态成页面的方式也是会不留神遇到问题，尤其结合后退或者刷新操作！

简单的如果想整合出一个类似微店的应用，包含有商品列表、商品详情、分类、搜索综合起来，还是会有很多不合实际的意外，mobilebone最好可以结合场景重点做一些动态页面的交互demo。

**Comment by zhangxinxu** [comment]
感谢反馈，有时间，我会好好看看，消化下这些建议~

**Comment by xuetian120** [comment]
你写的例子：
&lt;li&gt;&lt;a href=&quot;root-reload.php?id=1&quot; data-ajax=&quot;true&quot;&gt;根地址不缓存1&lt;/a&gt;&lt;/li&gt;
点击到最后一步到页面/test/ajax-html/index.html#&root-reload.php?id=8
页面内容
document.getElementById("idShow").innerHTML是： ，应该结果是8.
这里的document.getElementById("idShow").innerHTML是后面本来应该执行data-callback="root_reload"定义的方法，显示为8，这里不执行显示了空！

**Comment by xuetian120** [comment]
接着示例
&lt;li&gt;&lt;a href=&quot;root-reload.php?id=1&quot; data-reload&gt;根地址不缓存1&lt;/a&gt;&lt;/li&gt;
这里加上data-reload不缓存，
点击到最后一级test/ajax-html/index.html#&root-reload.php?id=8
此时点击浏览器后退按钮，观察dom变化，发现此处存在了相同的二个page。
反正我做类似多级分类的效果，不管是是否设置data-reload，都遇到了不同的问题，经常在后退操作时出现空白页面，希望检查一下。

**Comment by xuetian120** [comment]
var root_reload = function() {
    console.log('callback')
    var show = document.getElementById("idShow"), should = document.getElementById("idShould");
    console.log(should.innerHTML)
	if (show && should) {
		show.innerHTML = should.innerHTML;
	}
};

会发现
firstinto excuted!
callback
1
8: script excuted!
这样的结果
或者
firstinto excuted!
callback
8
1: script excuted!

**Comment by zhangxinxu** [comment]
今日好好处理了下~~欢迎继续反馈~

**Comment by xuetian120** [comment]
这种多级分类的情况，结合实际项目，我验证了很多次，都是存在或多或少的问题，不可行的，经常出现时四级页面回到三级页面时，页面呈现空白！

最后我直接把每个分类定义成了不同的id来处理，就是每个分类对应不同的page，一了百了！如果实在不好处理，多级同id可以不支持！

但是似乎由此引起了如下这类问题，希望引起重视，走读一遍代码细节：

怪事了，现在出现Mobilebone会自动清空一些dom结构。

比如一个列表页面，配置data-reload；点击列表进去详情，点击后退回到列表；再点击另一个列表进去详情，点击后退到列表，此时观察dom，发现详情的dom结构被自动清掉了，这明显是不可行的！

目前开发过程遇到了严重问题，比如列表页面A，点击一个列表项目到详情B，操作详情B会通过Mobilebone.createPage创建一些过程页面，如果通过上述往复操作，详情B的页面结构清理掉了，导致在操作过程页面时需要更新B页面上的显示内容时，因为B的dom不存在根本操作不了，从过程页面后退到B页面，此时很怪异的又会从内存中显示回的旧页面结构！（ps：进一步发现这里删除的dom应该还在内存中，但是从页面上已经被清理了，这里的处理太不合理了，希望马上修正！）


所有，强烈建议不能自动清理页面dom结构！

**Comment by kuangpeng** [comment]
接着示例
<li><a href="root-reload.php?id=1" data-reload>根地址不缓存1</a></li>
这里加上data-reload不缓存，
点击到最后一级test/ajax-html/index.html#&root-reload.php?id=8
此时点击浏览器后退按钮，观察dom变化，发现此处存在了相同的二个page。
反正我做类似多级分类的效果，不管是是否设置data-reload，都遇到了不同的问题，经常在后退操作时出现空白页面，希望检查一下。

-----------------------------------------
这个情况我也遇到了，（我用的是最新版的）请尽快修复！

**Comment by kuangpeng** [comment]
还有历史记录问题， 返回上一页很混乱，跳到了上上一页，我用的是js代码控制返回，然而点浏览器的返回按钮却没问题

**Comment by kuangpeng** [comment]
还有历史记录问题， 返回上一页很混乱，跳到了上上一页，我用的是js代码控制返回，然而点浏览器的返回按钮却没问题

**Comment by zhangxinxu** [comment]
当年自己还是能了点，现在data-reload重新优化了下，可以指定data-reload值当作一个组页面进行控制了，以前的判断很混乱。前进与后退也优化了很多，不会出现太多重复记录，以及方位顺序也优化了下，不过还没大规模测试，我稍后发布下。
