### ISSUE TITLE
Mobilebone.onpagefirstinto设计问题

### ISSUE THREAD

**Issue by xuetian120** [zhangxinxu/mobilebone#138]
遇到的情况，页面进行重新请求了，但是不执行Mobilebone.onpagefirstinto，只执行Mobilebone.callback！
举例做搜索时：
搜索页面结构：
<input type="text" id="searchKey" placeholder="快速找"><input type="button" value="搜索" id="searchBtn">
点击搜索执行
Mobilebone.ajax({
     url: 'page/product.html?keyword=' + keyword,
     success: function() {
     }
});
切换到搜索结果，此时再返回到搜索页，如果搜索关键字一样，此时虽然重新请求了page/product.html页面，但是不会执行Mobilebone.onpagefirstinto里面的初始化方法，这里不合理，既然重新请求了页面回来，应该Mobilebone.onpagefirstinto与Mobilebone.callback里面的内容都会执行。

**Comment by xuetian120** [comment]
测试发现url不变，使用Mobilebone.ajax虽然会重复请求页面内容，但是都不会再次执行Mobilebone.onpagefirstinto

**Comment by zhangxinxu** [comment]
好的，感谢反馈~

**Comment by xuetian120** [comment]
经过反复测试，对于ajax处理此类url —— test.php?id=1仅参数的变化（id=2、id=3、id=4...），同一page中替换显示内容，这时浏览器history记录很乱，浏览器后退操作与打开操作不一样，会忽略很多记录不显示。

**Comment by zhangxinxu** [comment]
刚提交并合并了一波，今天回家早，我好好测试了下，还顺便更新了部分文档。

**Comment by xuetian120** [comment]
好，我测试一下看看，感谢！！！
