### ISSUE TITLE
当ajax请求页面时，response中包含svg文件时，页面title会失效

### ISSUE THREAD

**Issue by woaixiangbao** [zhangxinxu/mobilebone#144]
事情是这样的，当转场是通过ajax去请求新的page页面，而这个新的page页面只是html片段，并不包含head和body之类的，只是一个div。那么，当这个div中包含svg文件（svg文件指的是SVG Sprite文件，你博客中介绍过，而这类代码中一般会包含< title > xxx< / title >标签的。这样就会导致Mobilebone.createPage 这个方法中的create_page.setAttribute("data-title", create_title.innerText);这个失效。因为xml中的标签没有innerText方法。

所以。。。难道还要判断一下是否是SVGTitleElement才行？

我现在是遇到了这样的问题，因为转场请求过来的页面中包含svg，所以即使设置了data-title什么的都不管用，都会返回undefined，不仅如此，这个undefined还是个字符串，所以在你源码的第285行：

if (title) {
				document.title = title;
				if (header) {
					header.innerHTML = title;
					header.title = title;
				}
			} else if (first_page == pageInto && !pageOut && document.title) {
				// set data-title for first visibie page
				pageInto.setAttribute("data-title", document.title);
			}

还是会走到if块里面去，所以最终依然页面的标题是undefined。

不知道我有没有描述清楚，大概就是这样了。

**Comment by zhangxinxu** [comment]
好的，非常好的反馈~
