### ISSUE TITLE
sap页面原生无法获取webview的history变化

### ISSUE THREAD

**Issue by xjchenhao** [zhangxinxu/mobilebone#149]
张大神，sos紧急求助，spa页面嵌入webview中，原生无法获取url的变化，无法实现捕获url制作“后退“按钮的的历史记录怎么办？他们拿到的url只拿到最初的url  `index.html`

**Comment by julor** [comment]
webwview的bug

**Comment by xjchenhao** [comment]
安卓后来拿到了，iOS死活拿不到，坑爹了。不会每次都要发个交互协议给原生，说我页面跳转了吧。。
