### ISSUE TITLE
loading 显示没有动画

### ISSUE THREAD

**Issue by zhongjq** [zhangxinxu/mobilebone#156]
直接执行代码
document.querySelector('body > .mask').style.visibility = 'visible';
loading 不会旋转，求解。
另外觉得mobilebone提供类似Mobilebone.loading('show')和loading('hide');的接口

**Comment by zhongjq** [comment]
目前我把ele_mask.style.visibility改成 ele_mask.style.display 动画就可以了

**Comment by zhangxinxu** [comment]
你好，可以告知具体使用场景吗？是哪个设备再什么情况下loading没有旋转？我桌面和我自己手机测试，loading转得很开心。

**Comment by zhangxinxu** [comment]
不管怎么，已经修改成display隐藏~

感谢反馈！
