### ISSUE TITLE
手机打开的页面，回退后旧页面的位置会回到最顶，而不是之前浏览的位置

### ISSUE THREAD

**Issue by oqy** [zhangxinxu/mobilebone#159]
张哥你好，有个问题需要请教你：

我有一个列表页面，数据是页面打开后通过异步加载的，使用mobilebone点击某条记录加载详情页面，再点击回退后，在PC测试时可以回到列表页面之前的浏览位置，但通过手机打开网页时，回退列表页面则会回到页面顶部而非此前的浏览位置。我当前使用的mobilebone版本是2.4.2，在安卓4和ios7、ios8的浏览器和微信都测试过，情况都一样，请问这个问题会与列表异步加载数据有关吗？有没有方法解决？谢谢！

**Comment by zhangxinxu** [comment]
好的，我回头看看~

**Comment by oqy** [comment]
好的，谢谢！

现在我们做了一个临时的解决方案，进入详情page时记录列表page里列表container div的scrollTop，回退到列表page时再将保存的scrollTop值设回container div里

**Comment by zhangxinxu** [comment]
你好，我使用比较简单的页面测试，没能重新此问题，可能需要特定情境才能复现，我什么时候实际遇到类似问题再看看什么原因。
要说解决方法，你现在的记录scrollTop值是非常棒的方法！

**Comment by chfeizy** [comment]
检查下 callback 里IScroll是不是执行了两遍
我之前也有这个问题
是后退后又执行了一遍IScroll

**Comment by oqy** [comment]
好的，谢谢两位的建议，我再检查一下
