### ISSUE TITLE
作者放弃维护了？

### ISSUE THREAD

**Issue by julor** [zhangxinxu/mobilebone#160]
首先感觉这个框架满足小型项目需求，小巧！
可是最近很多反馈的问题没有回答，难道作者停止维护了？
求更新

**Comment by zhangxinxu** [comment]
你好，没有，之前一有问题就处理，都没时间写文章。所以现在改成一段时间后一起处理。

**Comment by xuetian120** [comment]
做好一个精品先，有些问题不及时修复处理，他人很难用起来，用起来也没有信心，毕竟提交的问题都是现实遇到的紧急问题，不然也不会过来反馈！
ps：大多好的插件都应该是响应更新很快的，大家才乐于用、乐于持续反馈！

**Comment by xuetian120** [comment]
我一度以为也是作者放弃维护了
