### ISSUE TITLE
过场动画，也就是二个页面切换的动画，好像不是很流畅啊，有时有白边

### ISSUE THREAD

**Issue by hinadong** [zhangxinxu/mobilebone#165]
二个页面切换时，动画好像有点问题，感觉前一个页面早早的已经消失，后面的一个页面才切换过来，二个页面之间有白色背景，这是iPhone 5S上的测试，不知道是不是与CSS3的动画时间设置有关系，以上测试都在在demo文件基础的测试，没有作任何改动！

**Comment by xuetian120** [comment]
这个我也遇到了，切换过程不流畅！尤其是基本切换，理论上应该是很快的，但因为连loading过程都没有，切换又不够流畅反而显得延迟较大。

还有就是对应a链接的处理，似乎很多手机点击后，响应也是延迟较大！对于直接写click事件反而响应很快！

**Comment by weeksun23** [comment]
我也遇到了！！！前一个页面早早的已经消失，后面的一个页面才切换过来，二个页面之间有白色背景！！！

**Comment by xuetian120** [comment]
测试过程还遇到过，快速的连续点击多次，导致空白页面出现！

通过事件，结合Mobilebone.createPage创建的页面，更容易发生快速多次连续点击，出现一个空白页面！测试同学手贱，喜欢快速多次连续点击看结果，稍微延时点响应就会不停的点击去测试。

**Comment by zhangxinxu** [comment]
大家好，是新版本这样吗？我今天刚修复了默认slide过场有白色缝隙的问题，对了，是更新CSS文件。

**Comment by xuetian120** [comment]
实际情况，一个页面如果有上拉加载更多，多载入一些内容最后dom结构比较复杂，加上还有列表图片，切换起来就容易出问题，很多安卓机器都会卡在一半，闪动一下，出现空白或者切换完后闪显等情况都有！

**Comment by julor** [comment]
新版本没有问题了，以前的版本css有问题，我看到已经修复

**Comment by zhangxinxu** [comment]
安卓机器的性能问题只能慢慢等待了~
