### ISSUE TITLE
另外，HTML5里面有个pushstate的接口，也就是twitter等在网址中用的#!  这个，通过这个接口结合AJAX也可以实现类似的功能

### ISSUE THREAD

**Issue by hinadong** [zhangxinxu/mobilebone#166]
另外，HTML5里面有个pushstate的接口，也就是twitter等在网址中用的#!  这个，通过这个接口结合AJAX也可以实现类似的功能。这个技术好像称之为Pjax ,感觉更简单一点，请问作者，mobilebone相比Pjax有何改进和优势？

**Comment by zhangxinxu** [comment]
你好，一个是UI组件，一个是技术方案。Mobilebone使用了类似Pjax的技术。
