### ISSUE TITLE
某种布局下页面内容无法重绘的问题

### ISSUE THREAD

**Issue by wangwen1220** [zhangxinxu/mobilebone#184]
一个绝对定位元素下嵌套一个固定定位元素，再经过 mobilebone 转场，用 JS 改变固定定位元素的内容，浏览器中就无法重绘出来了

**Comment by zhangxinxu** [comment]
固定定位内容父元素如果有transform设置，会变成绝对定位效果。尝试固定定位元素放在页面之外。
