### ISSUE TITLE
不同页面打开相同的连接会生成多个子page...

### ISSUE THREAD

**Issue by isszz** [zhangxinxu/mobilebone#189]
我在首页有一个连接入口,然后在首页点击导航进去还有一个相同的连接的入口 点击后生成一个子page 然后返回点击首页那个相同的连接还会再次生成一个子page...且第二次生成的页面不会执行js...

**Comment by isszz** [comment]
我发现这个问题是因为url的路径...
/user/1, /user/2  如果这样点击多个用户连接会生成多个相同id的页面;
/user?uid=1, /user?uid=2 这样就只生成一个 id的页面
不知道这个算不算bug呢- -?

**Comment by isszz** [comment]
又发现一个问题...在同个页面点击相同根页面参数不同 会再次创建一个页面 且删除之前的页面然后点击返回后页面就空白了..

**Comment by zhangxinxu** [comment]
已经使用data-reload="your-page groupID"优化了。
