### ISSUE TITLE
关于返回键回退页面的问题

### ISSUE THREAD

**Issue by bajian** [zhangxinxu/mobilebone#201]
以官网demo为例：[基本切换主页](http://rawgit.com/zhangxinxu/mobilebone/master/test/base-slide/index.html#&pageHome)
如果用户主页中点击页面1再点返回，再点页面2再点返回。
这个时候，如果用浏览器返回键或者手机返回键5次，就会发现他按历史进入的记录依次回到页面2-主页-页面1-主页-彻底关了主页。
我想表达的就是如果用户只是单纯的想关闭页面的话，需要回退很多个页面。而如果我们测试的主页不是最底部的页面的话，那问题就更严重了。。不像app那样点一下就能退出当前Activity页面，而是要点击N次。。
不知道怎么解决这个问题呢？
就是A->B->C->A的话，B、C页应该是要被清除的历史。。而不会被返回键返回

**Comment by dongshixiao** [comment]
你好,请问这个问题解决了吗?

**Comment by bajian** [comment]
以前好像是自己解决了，现在忘记了，很久没用这库了。现在都使用Vue了，Vue-router实现很不错 @dongshixiao

**Comment by dongshixiao** [comment]
有个  data-history="false" 加链接上就好了. vue目前公司不采用...

**Comment by zhangxinxu** [comment]
data-history="false"
