### ISSUE TITLE
能否上下切换page

### ISSUE THREAD

**Issue by Zhang-Yida** [zhangxinxu/mobilebone#206]
在网上找了几个开源的项目 比如说 swiper swipe2 ， 想问一下，这个插件是否支持两个page上下切换 ， 并在每个page中自定义高度， 比如说第一个page的高度是正常的手机页面显示的大小， 而第二个页面内容比较多， 在第二个页面 ontouch 的时候能向下展示这个页面的内容， 而不是因为滑动而跳到第三页。。 在线等，麻烦了

**Comment by zhangxinxu** [comment]
可以的，文档页面就是上下滑动的，http://rawgit.com/zhangxinxu/mobilebone/develop/docs/index.html
可参考 Mobilebone.classAnimation
