### ISSUE TITLE
与bootstrap 模态css冲突

### ISSUE THREAD

**Issue by moonrailgun** [zhangxinxu/mobilebone#208]
**bootstrap** 与 **mobilebone**的css文件公用fade和in类。会造成动作冲突相互覆盖。
具体的表现为：
- 模态背景变为全黑并有很明显的动画掉帧

**Comment by zhangxinxu** [comment]
mobilebone采用的CSS动画策略，基本上是业界约定俗成的规范，mobilebone这边目前不会做调整的。
