### ISSUE TITLE
两次加载根目录相同url，后退后变空白

### ISSUE THREAD

**Issue by Caijt** [zhangxinxu/mobilebone#209]
因为我用thinkphp框架了，所以所有的url都是index.php?s=/Admin/index/index这样，所以对于插件来说根目录都是相同的，所以造成一个问题，比如我用ajax加刷一个页面，这个页面又有一个ajax点击链接，点击后，加载后，再后退，就变成空白的了，因为我的url都是index.php为根目录的，所以再加载时，总会把之前的删除掉
如果我把链接改成其它根目录的就不会出现这种现象
我希望可以弄一个可以有一个属性（例如data-new），那么这个ajax请求就不会删除之前同样根目录的page，而是单独创建一个独立的page

**Comment by Caijt** [comment]
自己解决了
在源js文件里350行附近，以下代码下面
if (options.id) {
	// eg. get 'ajax.php' from 'ajax.php?xx=1'
	pageid = pageid.split("?")[0];
}
增加以下代码后，只要在a标签上增加data-pageid='页面id'，这样就可以让根目录相同的页面，重复加载后不会被删除了，只会删除pageid一致的页面
if(options.target){
	options.pageid=options.target.getAttribute("data-pageid");
	if(options.pageid){
		pageid=options.pageid;
		pageInto.setAttribute("data-pageid",pageid);
	}
}else{
	pageid=pageInto.getAttribute("data-pageid")||pageid;
}

**Comment by zhangxinxu** [comment]
很赞的处理，可否Pull一个request，我合并下！可以在源码中注释你的名字和issue id~
