### ISSUE TITLE
ajax请求数据，回调之后再切换页面该如何实现

### ISSUE THREAD

**Issue by lichenbuliren** [zhangxinxu/mobilebone#213]
你好，我在你的博客中看到这么一句话：

> 虽然Mobilebone提供了直接请求JSON数据的方法，并提供了视图渲染接口。但是，以我个人经验，对于实际开发，这种实现策略是不推荐的。我认为更好的实现方法应该是这样的。页面骨架，也就是page主体，也就是一个空div默认就载入，然后所有的切换都是基本切换，而不是Ajax切换。在切换即将开始的时候（回调），您就可以使用自己，例如Zepto的Ajax方法去请求你需要的JSON数据，做你任何想做的事情，完全没有Mobilebone的限制。

我想实现的就是你这里说的问题，但是我没有找到那个即将开始的时候的回调在哪？
我页面上有个提交按钮，在点击提交的时候，我会调用ajax请求提交表单数据，我想在回调成功里面再执行转场，请问能否实现这个的逻辑呢？

谢谢！

**Comment by zhangxinxu** [comment]
可以的。Mobilebone.transition()方法，可以自如控制转场。 使用可参考文档说明： http://rawgit.com/zhangxinxu/mobilebone/develop/docs/index.html#&Mobilebone.transition.html

**Comment by liuzengwei** [comment]
Mobilebone.transition 请问这个方法有没实例呢！  新手不知怎么用它。。。

**Comment by zhangxinxu** [comment]
上面文档地址有问题，使用这个：https://www.zhangxinxu.com/GitHub/mobilebone/docs/#&Mobilebone.transition.html
