### ISSUE TITLE
请问手机端输入框搜索input 如何禁止点击弹出手机键盘搜索按钮后切页面？

### ISSUE THREAD

**Issue by yangjunwu** [zhangxinxu/mobilebone#221]
会出现切页错误，请问如何避免 点击后切页
$("#searchInput").bind("search",function(event){
					isearch.isearchbox.html("");
					isearch.size = 1;
					isearch.svalue = $.trim($("#searchInput").val());
					isearch.loadSearchData(isearch.svalue,1);
					event.returnValue = false;
				    event.preventDefault();
				    event.cancelBubble = true;
					event.stopPropagation();
					return false;
				});
会出现错误页面
<div class="page in" data-title="抱歉，出错了" style="display: block;">

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>抱歉，出错了</title>
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=0">

**Comment by yangjunwu** [comment]
可以在form表单加data-ajax="false" 就能解决

**Comment by zhangxinxu** [comment]
或者全局设置Mobilebone.captureForm = false;
