### ISSUE TITLE
Mobilebone.remove() 方法bug

### ISSUE THREAD

**Issue by t9044** [zhangxinxu/mobilebone#231]
文档上是说remove方法可以传入页面id, 但是如果页面本身就是读取外部文件加载的, 例如使用Mobilebone.ajax加载的页面, 这个时候内部的store容器内的键名是外部文件名. 所以使用remove方法时也需要使用完整的外部文件名.
例如ajax加载了一个url为template/student_employ_edit.html的外部文件. 
`
Mobilebone.ajax({
     url: 'template/student_employ_edit.html'
});
`
那么调用remove方法时, 也需要使用
`Mobilebone.remove('template/student_employ_edit.html');`

**Comment by zhangxinxu** [comment]
就是这么设计的，我稍后更新下文档，细化下这个方法。
