### ISSUE TITLE
JS中如何做跳转呢？还有js中如何获得url问号后面的参数？

### ISSUE THREAD

**Issue by AveiShriety** [zhangxinxu/mobilebone#236]
您好！我有个模板页面生成20条文章概要的记录，点击后进入不同的详情页面，那我如何在**js中进行跳转**，我目前是使用的
<pre>
mobilebone.ajax({
  url : './companylifedetail.html?articleid=' + articleid + "&_ts=" + (new Date().getTime()),
  success : function(data) {
  }
})；
</pre>
存在的问题：
1.会产生好多的.page，我的意向是能够像createPage()方法那样可以进行remove操作，相同类型的.page只保留一个；
2.如果用createPage()的话又不可以分享链接进行分享
3.如果用transition()的话，我是没有也不打算预先定义.page容器div给这块内容的

还有 js中 location.search好像获取不到问号后面的参数值？那该要如何获取url参数呢

**Comment by zhangxinxu** [comment]
ajax()/createPage()/transition()都属于进阶用法，实际开发一般很少用到。
底层的实现逻辑是这样的：点击 <a> 元素 → ajax() → createPage() → transition()
因此建议直接创建 `<a>` 元素，remove操作可以在 `<a>` 元素上设置 `data-reload="anySameId"`。
参数获取可以在任意的生命周期事件函数中 使用 `options.query` 获取。

假设有全局的回调方法：
```js
Mobilebone.callback = function (pageInto, pageOut, options) {};
```
则 `options.query` 就是完整的 URL 参数。

您可以访问 Mobilebone 的教程了解更新信息：https://www.zhangxinxu.com/github/mobilebone/docs/guide/#&indexPage
