### ISSUE TITLE
data-url貌似只适用于a标签

### ISSUE THREAD

**Issue by yuxianwen** [zhangxinxu/mobilebone#43]
觉得可以变得更强大一些，任何标签都可以。个人建议。

**Comment by zhangxinxu** [comment]
你好，mobilebone设计的初衷是：没有mobilebone，是个普通页面，有了mobilebone，就是单页面。所以，我思量了下，适用于任何标签有些与当初设计不符，因此目前是不会修改。不过，你的建议我会记在心上，后续可能会以接口形式提供此功能。
