### ISSUE TITLE
异步添加的data-ajax="false"无效怎么破？

### ISSUE THREAD

**Issue by xjchenhao** [zhangxinxu/mobilebone#44]
异步添加的新闻列表、产品列表链接 想让它正常跳转

**Comment by zhangxinxu** [comment]
你好，data-ajax判断来自document委托，所以，理论上讲，是不会无效的，可能受其他场景或条件影响（如不是a标签），不知可否提供可访问的原型页面或者源代码，我来看看是怎么回事？

**Comment by xjchenhao** [comment]
额，检查出来了，是iscroll关闭了默认事件。

        var myScroll = new IScroll('#pageList', {
            scrollbars: false,
            mouseWheel: true,
            click: true,        //这个要开启
            probeType: 2,
            startY: 70
        });
