### ISSUE TITLE
关于离线应用

### ISSUE THREAD

**Issue by dancinglone** [zhangxinxu/mobilebone#45]
小白求指教
我想做离线应用，通过webview访问静态页面（而且页面较多不适合做单页面），但很不能ajax加载的话，会出现一些问题，例如，data-rel在不是单页面的情况下，就不无法生效了。请问应该怎么办呢？

**Comment by zhangxinxu** [comment]
你好，如果是data-rel不生效，可以在直接加载的页面引入mobilebone相关资源；如果是data-rel对应的内容不生效，假设指向的是页面，需要使用ajax地址，如果是单纯的返回，可以href为"javascript:;" 不知你是哪种情况？

**Comment by dancinglone** [comment]
在本地不能用ajax怎么办啊？不能用ajax我从首页进入子页后，就是打开了另一个页面，那我按链接<a href="<a href="javascript:history.back()" data-rel="back">" data-rel="back">就不能反向滑动返回了（请原谅我小白会犯低级错误）

我就是刚在您博客提问那个，我发现<a href="javascript:history.back()" data-rel="back">兼容性似乎是有问题的，不知道是不是我写错了

非常感谢您刚刚的及时回复！

**Comment by zhangxinxu** [comment]
你好，是不是JS脚本挂掉了，而导致链接走传统跳转了？

**Comment by dancinglone** [comment]
没有挂啊，是在本地打开的，就不是ajax加载了，但又不是像您的demo那样是单页面，我的是多页面的，所以data-rel="back"就没用了吧？

**Comment by zhangxinxu** [comment]
你好，file:// 协议打开的页面是无法使用ajax的，你看下是不是这种情况？

**Comment by dancinglone** [comment]
衷心感谢您的回复！！
是的，file://协议下打开的页面是无法使用ajax的，但项目页面太多，不能做成单页面，那我还能实现页面过场效果吗？有什么好办法吗？求指教！

**Comment by zhangxinxu** [comment]
你好，装个环境，使用http://访问即可（window自带iis, 或者下载Wamp），实际开发的线上页面都不会是file://协议的。

**Comment by dancinglone** [comment]
但是，我的项目要求是在手机上用安卓应用以及ios应用的webview控件访问静态页面啊，这样有办法用http协议访问吗？

**Comment by zhangxinxu** [comment]
你好，控件协议也是可以使用请求的~

**Comment by dancinglone** [comment]
请求本地html也可以吗？能用ajax请求本地的html文件吗？为了节省用户流量，html文件是在安装应用时就把它们也顺带下载的。

**Comment by zhangxinxu** [comment]
可以的，让客户端将对应HTML内容返回过来就可以。

**Comment by dancinglone** [comment]
是吗，可以说具体一点吗?具体是怎样让客户端将对应HTML内容返回过来啊？

**Comment by zhangxinxu** [comment]
那就要问你们团队里面开发iOS或Android应用的开发了~

**Comment by dancinglone** [comment]
哦哦，好的，我问问他们，非常感谢您！非常感谢您的mobilebone! 期待您的进一步开发！

**Comment by dancinglone** [comment]
昨天提的问题终于解决了，方案是在应用内嵌入一个server。 非常感谢您！
