### ISSUE TITLE
如何在页面加载的时候触发$(document).ready(function(){}) 中的事件

### ISSUE THREAD

**Issue by anyudi** [zhangxinxu/mobilebone#46]
非常好用，码神！不过遇到个问题：
除了Mobilebone.callback = function() {};
在页面跳转的时候可以触发load 事件，还有没有其他的方式？
因为我有很多js 是在jquery的$(document).ready(function(){}) 中执行的

**Comment by zhangxinxu** [comment]
你好，<code>$(document).ready(function(){}) </code>中的事件属于私有事件，你可以借助全局对象$将一些事件暴露出来，然后就可以在page元素上设置<code>data-onpagefirstinto</code>（执行1次）或<code>data-callback</code>（每次都执行）值为事件关键字，实现你要的效果。

例如：
<pre>$(document).ready(function(){
    var funA = function() {};
    var funB = function() {};

   $.extends({
        a: funA,
        b: funcB
    });
});</pre>

HTML方面：
<pre>&lt;div class="page out" data-onpagefirstinto="a" data-root="$">&lt;/div></pre>

于是，此该页面第1次载入时候，就能够调用<code>$(document).ready(function(){}) </code>中的事件<code>funA</code>了。

**Comment by anyudi** [comment]
回复速度很快！
所有的页面基本上都是走的ajax跳转，就是 <a href="one.html"></a>
引用你上面的代码后，one.html页面结构如下：
$(document).ready(function(){
    var funA = function() {
	     alert("AAA")
    };
   $.extend({
        a: funA
    });
});

<div class="page out" data-callback="a" data-root="$">
    <div class="header">
      <h1>A标题</h1>
    </div>
    <div class="content" id="#content1">
      <ul>
        <li>第一个页面</li>
        <li>第一个页面</li>
        <li>第一个页面</li>
        <li>第一个页面</li>
        <li>第一个页面</li>
        <li>第一个页面</li>
      </ul>
    </div>
    <div class="footer">
      <h1>A标题</h1>
    </div>
</div>


·····那个alert没有弹出来， 说明funA 没有执行····不知道我的页面哪里出了问题··谢大神了

**Comment by anyudi** [comment]
·······额  代码直接生成页面了····

**Comment by anyudi** [comment]
<html>
<body>
<div class="page out" data-callback="a" data-root="$">
    <div class="header">
      <h1>A标题</h1>
    </div>
    <div class="content" id="#content1">
      <ul>
        <li>第一个页面</li>
        <li>第一个页面</li>
        <li>第一个页面</li>
        <li>第一个页面</li>
        <li>第一个页面</li>
        <li>第一个页面</li>
      </ul>
    </div>
    <div class="footer">
      <h1>A标题</h1>
    </div>
</div>

</html>
</body>

**Comment by anyudi** [comment]
<code>
<html>
<script>
$(document).ready(function(){
var funA = function() {
     alert("AAA")
};
$.extend({
     a: funA
});
});
</script>

<body>
    <div>
        <div>
          <h1>A标题</h1>
        </div>
        <div id="user-content-#content1">
          <ul class="task-list">
            <li>第一个页面</li>
            <li>第一个页面</li>
            <li>第一个页面</li>
            <li>第一个页面</li>
            <li>第一个页面</li>
            <li>第一个页面</li>
          </ul>
        </div>
        <div>
          <h1>A标题</h1>
        </div>
    </div>
</body>
</html>
</code>

**Comment by anyudi** [comment]
<pre>

          <ul class="task-list">
            <li>第一个页面</li>
            <li>第一个页面</li>
            <li>第一个页面</li>
            <li>第一个页面</li>
            <li>第一个页面</li>
            <li>第一个页面</li>
          </ul>
</pre>

**Comment by anyudi** [comment]
解决了，这些方法要都写在index 页面才行····

**Comment by anyudi** [comment]
3QQQQQQ

**Comment by dancinglone** [comment]
你意思是子页面的js吗？ajax加载只加载了“.page‘,子页面的<script></script>是不加载的，所以就不生效啊。不一定要写在index的，可以用data-success属性的。（不知道我有没有误会你的问题）
