### ISSUE TITLE
切换过来的页面里面无法fixed另外一个div的问题

### ISSUE THREAD

**Issue by woaixiangbao** [zhangxinxu/mobilebone#47]
您的test里的例子里有一个固定header和footer的页面，但是，也有一种情况是：当某单独页面需要一个固定的footer2或者固定的header2的时候就不太好用了。

我在某个页面里使用了position：fixed;，但是当进入这个页面以后，这个固定定位的元素就失效了。

复现的方法是这样的：

在你的项目下找到test/fixed-header-footer/index.html，将这个文件的第27行，也就是< div id="page1" class="page out" data-title="页面1" >< div class="content" >页面1内容...< /div >< /div >修改为下面的代码：

< div id="page1" class="page out" data-title="页面1">
    < div class="content">
        < p>页面1内容...</p>
        < p>页面1内容...</p>
        < p>页面1内容...</p>
        < p>页面1内容...</p>
        < p>页面1内容...</p>
        < p>页面1内容...</p>
        < p>页面1内容...</p>
        < p>页面1内容...</p>
可以多复制几个，用来撑起页面。
        < div class="footer2" >
            这个是用来做测试的footer
        < /div >
    < /div >
</div>

然后在head标签的style里面加上下面的样式：

.footer2{
        position: fixed;
        bottom:50px;
        left:0;
    }

然后，切换到page1的时候你就能看到啦。

**Comment by woaixiangbao** [comment]
补充一点，是在ios下会失效，android下没问题。

**Comment by woaixiangbao** [comment]
好吧，我错了，我发现，根本用不着fixed，用absolute值就好了。sorry

**Comment by dancinglone** [comment]
单页面用fixed是不妥的啊
