### ISSUE TITLE
“backbone组合示例”有BUG

### ISSUE THREAD

**Issue by mattlin** [zhangxinxu/mobilebone#48]
“test的示例”中的 “backbone组合示例”有BUG。
git/mobilebone/test/backbone/index.html 文件中，36～38行：
    var render = function(page_in, page_out, json) {
    	        if(typeof json != "object") return;
        	var key = json.key, pageid = json.key + "Page";

render函数的参数json，json.key是undefined，json.response.key才是对的。

PS：是否是升级data-onpagefirstinto函数调用导致？

**Comment by zhangxinxu** [comment]
你好，对的，感谢纠正！版本升级与测试页面不同步导致~

**Comment by mattlin** [comment]
支持博主（这里应该说作者才对），很勤奋，更新很频繁，赞！ 
mobilebone是否有release版本，我想用在生产环境。

**Comment by zhangxinxu** [comment]
你好，已经release多个版本，https://github.com/zhangxinxu/mobilebone/releases

**Comment by mattlin** [comment]
谢谢zxx，支持mobileboneJS
