### ISSUE TITLE
微信综合实例 在手机上显示空白

### ISSUE THREAD

**Issue by liujmok** [zhangxinxu/mobilebone#49]
我在小米1s手机上自带的浏览器访问微信综合实例，显示一片空白，UC和FireFox可以正常显示，包括那个QQ实例也是一样。

**Comment by liujmok** [comment]
小米3上测试倒是正常。

**Comment by liujmok** [comment]
小米1s的版本是4.0.4，我今天将它升级到4.1.2，问题解决。
另外一台android 4.0.4的手机也遇到相同问题，我没有升级测试它。

**Comment by dancinglone** [comment]
不是吧。。。我在用webview做离线应用，希望没问题

**Comment by zhangxinxu** [comment]
@liujmok 你好，我手头上没有小米1S，可否帮我定位下问题所在，合作开发下，这就是开源协作霸气值所在~

我个人觉得可能是某些ES5方法不支持，导致报错~

**Comment by zhangxinxu** [comment]
@liujmok 现在看下还有没有问题~
