### ISSUE TITLE
请问兼容非常主流的wp不？

### ISSUE THREAD

**Issue by dancinglone** [zhangxinxu/mobilebone#50]
HTC8X wp8.1      <a  href="javascript:"  data-rel="back" ></>不能返回至前一page,而是直接返回到我之前访问的网站，按手机返回键也是。

**Comment by dancinglone** [comment]
点赞！！thx !

**Comment by dancinglone** [comment]
话说手机浏览器没有控制台，请问您是怎样做兼容性debug的呢？我只会用 alert()慢慢去排查。

**Comment by dancinglone** [comment]
试了最新版本，wp还是有这个问题。
<a href="javascript:void(0);" data-rel="back">   （会不会是我写错了啊）
还是不能返回。
我描述一下细节：
点那个链接后，页面只是闪了一下，url变了，但最后面只是“.com/”  没有homepage的id

**Comment by dancinglone** [comment]
安卓里偶然会发现点了是没效的，是我写错了吗？
我是这样写的
<a href="javascript:" data-rel="back">
难道是一定要写要返回的页面的id?  但在android和ios里大多数时候都没有问题了，暂时只是发现在android里偶然会无效。但跟wp是不一样的，是直接点了完全没变化（很少发现，而且没有控制台又不知道怎样调试）。而wp是另一种问题，history api应该是生效了（正如上面所说）只是page没有切换过去而已

**Comment by hjdshu** [comment]
我们是用Weinre 来调试，不知道博主是用什么工具调试的呢？

**Comment by dancinglone** [comment]
现在有空回来试了试新版本。发现之前的问题已经解决了！点赞，继续支持！
