### ISSUE TITLE
关于页面切换和ajax获取内容分离的问题

### ISSUE THREAD

**Issue by woaixiangbao** [zhangxinxu/mobilebone#51]
按照你文章中的建议：“我认为更好的实现方法应该是这样的。页面骨架，也就是page主体，也就是一个空div默认就载入，然后所有的切换都是基本切换，而不是Ajax切换。在切换即将开始的时候（回调），您就可以使用自己，例如Zepto的Ajax方法去请求你需要的JSON数据，做你任何想做的事情，完全没有Mobilebone的限制。”

这样的话，ajax过来的内容的事件，大部分都要绑定事件委托才好，比如都将事件绑定到document上。ios有个bug，有时候document不能绑定事件委托事件，在body上也不行。而且，据说document上的事件委托在性能方面也存在问题。

那么ajax新内容和绑定事件的先后问题最好的解决方案是什么？

**Comment by zhangxinxu** [comment]
之所以这么说，是因为JSON数据，是在mobilebone流程的中间处理，面对负责模板时候，可能会有局限性，所以建议，可以把JSON处理的整个流程放在mobilebone完成之后。

对于ajax新内容时间绑定——onpagefirstinto回调设计就是为了绑定事件，只在第一次进入时候执行。

**Comment by dancinglone** [comment]
感觉api文档不够具体，我这种小白真有点吃力，想在这个issue问个关于回调的问题:
代码：<li><a href="test.html" data-animationstart="subpageSuccess.dataLoad.callTest1">test</a></li>(ajax加载页面) 
发现函数是不执行的，而data-animationstart换成data-success是执行的。是因为ajax请求的回调要用“data-success”吗？要把过场回调写在ajax请求回调里面吗？
求指教

**Comment by zhangxinxu** [comment]
好的，文档我会逐步丰翼起来的。a上面的回调是ajax相关回调，data-animationstart之类是page相关回调，两者是分离的。

**Comment by dancinglone** [comment]
哦，原来是这样。感谢！
