### ISSUE TITLE
page里面需要固定定位元素的问题

### ISSUE THREAD

**Issue by woaixiangbao** [zhangxinxu/mobilebone#54]
好像我之前提过这个问题，当某个page需要一个固定在底部的元素的时候，由于用fixed失效，所以我使用absolute属性，但是某些时候会莫名其妙的不起作用。特别是在ios下，我发现有时候z-index会失效，我google了一下，说有可能是和transform属性有关，不过由于解释的过于复杂，我都看不懂，涉及层级之类的（stacking context）。

此处我说的底部是指只有这个page需要的一个底部，如果切换到别的page以后，别的page不能有这个底部的存在，我想不仅局限于一个固定在底部的元素，假如有需要置顶的元素或者别的固定定位的元素的话，应该都会出现这中问题。

不知道有哪位仁兄有比较好的解决办法没有。

**Comment by dancinglone** [comment]
我就是用absolute的，没发现问题，是不是你写错了

**Comment by zhangxinxu** [comment]
page内的底部会被跟着切换走，page平级的底部不会被切换走；特殊情况使用回调控制~

**Comment by zhangxinxu** [comment]
现在增加data-container/data-classpage两个自定义参数，可以实现page内页面的头尾固定效果~

**Comment by woaixiangbao** [comment]
今天我仔细排查了下问题：发现导致absolute失效的原因是我设置了-webkit-overflow-scrolling: touch，而且是全局设置的，我去掉这个就好了。

**Comment by woaixiangbao** [comment]
对不起，我又测试出问题了。
请访问这个地址
http://www.mashangju.com/kd100/mobilebone/test/ajax-html/index.html#&pageHome，
依然是打开第二项，然后，在大部分手机里，header和footer都是固定在固定的位置的，我测试了iphone4，iphone5，iphone5s，iphone6都没问题，android测试了好几个也没问题，发现问题的是coolpad手机不行，头尾不能固定。目前我手头只有这一个手机是不行的。这个手机的具体信息是这样的：
![image](https://cloud.githubusercontent.com/assets/1953879/5774287/33beec0a-9da7-11e4-8e9f-a85ef3322525.png)
不知道有没有人遇到过和我一样的问题。

**Comment by zhangxinxu** [comment]
这与Mobilebone其实没有关系的。稍微调整下结构，保证没问题，比方说，把头尾放在content的外面~

**Comment by woaixiangbao** [comment]
@zhangxinxu 谢谢！这么晚才来回复，的确和手机没关系，是我的结构写错了。我看了你在慕课网的关于absolute的视频，才发现我写错了，我把结构改过来以后就好了！谢谢你。这个应该可以关闭了。
