### ISSUE TITLE
返回页面回到页面顶部API

### ISSUE THREAD

**Issue by dancinglone** [zhangxinxu/mobilebone#58]
请问有没有返回页面回到页面顶部的API？如果之前打开的页面是向下滚动了，那再返回，它还是停留在之前滑到的地方，这样很多时候交互都不太友好。

**Comment by zhangxinxu** [comment]
你好，我个人觉得这Mobilebone不应该参与这样的交互。你可以写个全局callback~ 让<code>xxxElement.scrollTop = 0;</code>

**Comment by dancinglone** [comment]
也有道理。感谢指点！
