### ISSUE TITLE
如何判断当前页面是哪一个页面？

### ISSUE THREAD

**Issue by jscsscom** [zhangxinxu/mobilebone#59]
是否存在一个方法可以简单的判断当前页面是哪一个页面，比如用page的id或链接？

**Comment by dancinglone** [comment]
博文有说啊

**Comment by jscsscom** [comment]
哪里有说呀，没有看到呀。

**Comment by zhangxinxu** [comment]
你好，可以使用document.querySelector("."+ Mobilebone.classPage +".in");

**Comment by jscsscom** [comment]
谢谢。还有一个问题就是ajax请求时 data-rel过场方向的问题，麻烦看一下这个页面 http://w.wmfl.cn/index.php/Home/Mall/index/sid/1.html?debug=zhangrui.songyi 底部导航，第一个用的"#page-home"，后面三个用的ajax请求，只有和第一个转换时方向正确，后三个相互跳转时方向都是向左。
