### ISSUE TITLE
ajax请求时 data-rel过场方向的问题

### ISSUE THREAD

**Issue by jscsscom** [zhangxinxu/mobilebone#63]
http://w.wmfl.cn/index.php/Home/Mall/index/sid/1#&page-home 
这个例子，下方的导航切换时方向一直向左的，设置了data-rel="auto"，怎么回事？

**Comment by zhangxinxu** [comment]
如果页面Ajax请求，且没有缓存（data-reload），由于是新内容，都是从右打开的~
