### ISSUE TITLE
ajax请求的页面，链接无法点击

### ISSUE THREAD

**Issue by jscsscom** [zhangxinxu/mobilebone#64]
http://w.wmfl.cn/index.php/Home/Mall/index/sid/251.html?debug=zhangrui.songyi#&/index.php/Home/Mall/index/sid/251 
这个页面用ajax请求的html，链接为什么无法点击呢，帮忙看下，谢谢

**Comment by zhangxinxu** [comment]
地址是不是挂了啊？

**Comment by zhangxinxu** [comment]
如果是外链url没法点击，使用最新的JS试试~
