### ISSUE TITLE
zepto+mobilebone，使用tap时，出现触发2次的问题

### ISSUE THREAD

**Issue by liang24** [zhangxinxu/mobilebone#67]
最近在做一个单页的WebApp，使用seajs+zepto+mobilebone+iscroll这种搭配来开发，但是遇到一个比较坑爹的问题，就是使用zepto的touch模块时，会出现触发两次的问题，点击a标签也一样，会触发两次。

**Comment by zhangxinxu** [comment]
好的，感谢反馈，我看下~

**Comment by zhangxinxu** [comment]
你好，如何触发两次？是绑定touch事件每次tap两次执行，还是Mobilebone两次执行？

**Comment by zhangxinxu** [comment]
你好，据我测试，应该是iscroll的问题，你可能设置了iscroll <code>tap: true</code>, 但是，又没有使用iscroll的tap事件接口。于是会出现点击一次执行两次的情况。我把Mobilebone注释掉，也发现有这个问题。可见，你遇到的问题与Mobilebone没有关系。

**Comment by liang24** [comment]
十分感谢，的确是这个问题，困扰了我一阵子
