### ISSUE TITLE
咨询下 Mobilebone.ajax 的使用方法，谢谢！

### ISSUE THREAD

**Issue by wanjiaxun** [zhangxinxu/mobilebone#70]
咨询下 Mobilebone.ajax 的使用方法，谢谢！

**Comment by zhangxinxu** [comment]
支持一个参数，可以是<coce>a</code>元素，或者<code>form</code>元素，或者直接ajax发送数据，参数与jQuery的<code>$.ajax()</code>方法参数一样~

**Comment by 2yunyun** [comment]
搜嘎
