### ISSUE TITLE
ajax的实现方法里 formData的参数感觉有点问题

### ISSUE THREAD

**Issue by QETHAN** [zhangxinxu/mobilebone#71]
```
 formData = new FormData(trigger_or_options);
```

trigger_or_options 这个应该是个 json对象，FormData的参数是 FormElement。 求教

**Comment by zhangxinxu** [comment]
你好，这里是form元素：
<pre>
var tagName = trigger_or_options.tagName.toLowerCase();
if (tagName == "form") {
    // ...
    formData = new FormData(trigger_or_options);
}	
</pre>

**Comment by QETHAN** [comment]
哦。是Element元素的tagName属性。我以为是json对象的一个key
