### ISSUE TITLE
Mobilebone.jsonHandle 里边为什么直接返回 说JSON 没有parsing function 

### ISSUE THREAD

**Issue by QETHAN** [zhangxinxu/mobilebone#72]

**Comment by zhangxinxu** [comment]
如果使用JSON类型，由于Mobilebone不知道你需要的JSON处理规则，一定是需要自己额外添加jsonHandle处理方法的。但是，如果你忘记设置了，就会执行Mobilebone默认的jsonHandle方法，于是就提示使用者：“你还没有定义JSON解析方法！”

**Comment by QETHAN** [comment]
这样的话，每次ajax之前都要重写一下jsonHandle方法。不过比较习惯jquery ajax，直接使用回调里的参数data。如果要对data进行操作，在回调里写代码就是了。

**Comment by zhangxinxu** [comment]
你好，ajax提供了success, error等跟jQuery一模一样的回调接口，你可以做你想做的任何事情。第一个参数，就是返回内容。例如<code>data-success="funSuccess" data-type="json"</code>, 则：
<pre>var funSuccess = function(json) {
    // do something with 'json'
}</pre>

**Comment by QETHAN** [comment]
jsonHandle 对应 data-success ? 设置了data-success， 就等于说是 有了JSON parsing function ?

**Comment by zhangxinxu** [comment]
jsonHandle用来渲染出页面字符串并载入页面；如果你是单纯数据处理，就可以使用data-success.

jsonHandle不需要每次Ajax都重写(重写会覆盖会出问题)，我文章有举例，返回JSON可以加一个id标识符，于是：

<pre>
Mobilebone.jsonHandle = function(json) {
     switch (json.id) {
         case "homePage": {
             // do something
             break;
        }
        case "listPage": {
             // do something
             break;
        }
        case "detailPage": {
             // do something
             break;
        }
    }
};</pre>

**Comment by QETHAN** [comment]
那就要为 json 数据增加一个字段，或者 判断其他属性，来区分数据的类型。太操心了

**Comment by dancinglone** [comment]
"更好的JSON包括HTML加载建议
虽然Mobilebone提供了直接请求JSON数据的方法，并提供了视图渲染接口。但是，以我个人经验，对于实际开发，这种实现策略是不推荐的。我认为更好的实现方法应该是这样的。页面骨架，也就是page主体，也就是一个空div默认就载入，然后所有的切换都是基本切换，而不是Ajax切换。在切换即将开始的时候（回调），您就可以使用自己，例如Zepto的Ajax方法去请求你需要的JSON数据，做你任何想做的事情，完全没有Mobilebone的限制。
页面slide是有时间的，350ms, 这个时间点很可就就完成呈现了最终的页面。于是，我们看到的就是，一点击，页面slide，slide结束，内容呈现。哇哦哦~~操作感不要太流畅哦！而且技术上更可控，因为数据请求、处理与Mobilebone完全解耦。
当然，如果就是个原型页面、简单的静态页面，或者是不喜JS的小伙伴，依赖Mobilebone的Ajax整体请求与呈现策略显然是最好的选择，因为，你什么都不需要做~"

**Comment by dancinglone** [comment]
帖子里这样说
