### ISSUE TITLE
锚点和链接混用时，data-rel="auto"可能会混乱

### ISSUE THREAD

**Issue by Double-Lv** [zhangxinxu/mobilebone#74]
测试代码如下：

    <div class="header">
        <a href="#pageHome" data-rel="auto">首页</a>
        <a href="inner.html" data-rel="auto" data-container="container">页面2</a>
        <a href="inner2.html" data-rel="auto" data-container="container">页面3</a>
    </div>
    <div id="pageHome" class="page in">
        <div class="content">
            <p>首页内容</p>
        </div>
    </div>
    
首页那屏是一次加载，其他是ajax加载。这个时候data-rel="auto"自动滑入的左右顺序会乱掉。（首页和页面2之间的切换）

**Comment by zhangxinxu** [comment]
你好，<code>id</code>为<code>container</code>的<code>div</code>容器需要放在<code>id</code>是<code>pageHome</code>的page元素的后面。因为<code>data-rel="auto"</code>的时候，Mobilebone是根据页面在DOM流中的前后顺序判断方向的。

**Comment by Double-Lv** [comment]
get it
