### ISSUE TITLE
拥有href属性的a标签点击的时候，会自动生成一个ajax请求，但是某些时候会失效。

### ISSUE THREAD

**Issue by woaixiangbao** [zhangxinxu/mobilebone#75]
本来，点击一个a链接，mobilebone会自动将a链接的href的转换成一个ajax的请求，并且至少会在这个ajax的请求url中加入一个类似“?r=88787878”的参数（这个参数不是我加上的，我通过查看网络请求抓取到的，我猜应该是mobilebone自动加的参数吧）。但是，某些时候，当点击这个a链接的时候，并没有走ajax请求，而是页面直接跳转到href那个页面了（也就是a链接默认的那种动作）。

您文章中写道：“例如，我们请求ajax.html页面，该页面最好是完整的body > page结构。因为，就算页面JS挂掉，无法阻止默认链接行为，发生跳转，也不会影响可用性。但是，如果请求的是个动态页面，直接返回的是干净的HTML代码，如果没有page元素，则不能含有html以及body标签。”

我请求的是干净的动态页面，里面没有多余的html代码，连样式都没有，我查看了网络请求，js并没有挂掉，所以当“无法阻止默认链接行为”的时候，那个页面是完全不可用的。

现在还不太清楚到底那个环节出了问题。

我能发现的问题只是正常情况下请求的ajax地址是：“http://www.xxx.com/address/index?r=1422592433154"，这是没问题的。

出现问题时，网络触发的请求地址是：”http://www.xxx.com/address/index“。

总之是失效了。

**Comment by woaixiangbao** [comment]
今天在chrome 的inspect里面抓到了一个log是这样写的：

“
Uncaught SyntaxError: Failed to execute 'querySelector' on 'Document': '#tt_font=m&tt_daymode=1&tt_image=1&tt_from=app' is not a valid selector. 
”

定位到了mobilebone的下面这行代码：

			} else if (isSimple.test(hash) == true && (ele_in = document.querySelector(hash)) && ele_in.classList.contains(this.classPage)) { // 'ele_in' must be a page element


然后mobilebone的下面这部分代码的执行结果是false

“
/**
	 * page change when history change
	 **/
	window.addEventListener("popstate", function() {
		console.log(history.popstate);

”

**Comment by woaixiangbao** [comment]
我发现问题是因为一个#引起的，当某些时候一个页面的url加入了一些参数中带#的时候，mobilbone会判断错误。

**Comment by woaixiangbao** [comment]
我已经解决了这个问题了，不是mobilebone的问题，而是我的页面的参数的问题，我想办法把#
去掉以后就没事了。

**Comment by zhangxinxu** [comment]
我测了下，是mobilebone的问题，当多个<code>#</code>出现时候，会有问题~我修复下，感谢反馈~

**Comment by dancinglone** [comment]
越来越完善了，支持
