### ISSUE TITLE
addEventListener事件监听

### ISSUE THREAD

**Issue by dancinglone** [zhangxinxu/mobilebone#77]
请问如果我想给已加载的页面上的每一个按钮添加事件监听，使其被点击后通过dom获取被点击的按钮的数据，然后将数据转传到要进场的page , 应该怎样做比较妥呢？ 小白求指导！

**Comment by dancinglone** [comment]
又看了一遍帖子有几种思路了，我再试试看。

**Comment by mattlin** [comment]
如果使用jQuery，可以试试$(pageIn).find('#buttonId').click(function(){........});

**Comment by dancinglone** [comment]
在click的function里面做跳转吗？这样可以生成page然后进场吗？不是只有<a>才可以吗？求指教

**Comment by mattlin** [comment]
不好意思，刚才没有理解对你问题。“将数据转传到要进场的page ”，这个你可以在page进场后的回调方法中去获取你要的数据，例如从你的dom中获取你存的“被点击的按钮的数据”。

**Comment by mattlin** [comment]
page进场后的回调方法：callback(pageInto, pageOut, response → options) 每次过场页面进入的时候都会执行。详细见作者的博客：http://www.zhangxinxu.com/wordpress/2014/10/mobilebone-js-mobile-web-app-core/

**Comment by dancinglone** [comment]
我的问题这样不行的。因为我要监听我所点击的不同按钮获取相应的数据。最好我还是用addEventListener方法去做了

**Comment by zhangxinxu** [comment]
1. <code>data-preventdefault</code>可以让你在转场之前传数据（因为是单页应用，可以直接缓存）；
2. 回调方法中<code>options</code>参数中有个<code>options.trigger</code>，就是转场触发的点击按钮（如果有）。

**Comment by dancinglone** [comment]
好强大 ! 点赞！
