### ISSUE TITLE
data-rel="back"有bug?

### ISSUE THREAD

**Issue by dancinglone** [zhangxinxu/mobilebone#79]
在安卓webview里，我发现用<a href="javascript:" data-rel="back">返回上一page有时会出现点击无反应的现象（这时返回键也是无反应的。另外，刚刚在小米4上发现，偶然会出现点击两次才能返回的现象，出现这种情况后，返回上一页再进入再返回还是点击两次才能返回，连续的）。不知道是mobilebone的问题还是fastclick.js的问题。
我的Mobilebone不是最新的，我更新一下试试再回来反馈。

**Comment by dancinglone** [comment]
刚刚又发现，是要按四次才能返回。即使我是按了一两次，隔一会再按，也是一共按四次才有反应。
（注：这还是用旧的mobilebone）
如果这是已知原因的，新版已没有此问题，就忽略我好了。
新的我晚一点再测试。

**Comment by zhangxinxu** [comment]
你好，今天发布了2.4版本，如有此问题，还望告知~

**Comment by dancinglone** [comment]
点赞！我有空就测试一下回来反馈！
