### ISSUE TITLE
能否支持执行ajax请求的html页面中的javascript？

### ISSUE THREAD

**Issue by xingdonghai** [zhangxinxu/mobilebone#82]
有些特殊的需求是ajax请求了一个html页面，如果仅仅是作为显示和简单处理那么没有问题，但目前有个应用场景中需要执行ajax请求的这个html中的javascript，目前通过data-success来实现了，请问有更好的方式吗？

**Comment by zhangxinxu** [comment]
你好，这个需求是可以考虑的~ data-success是目前比较好的方法~

**Comment by xingdonghai** [comment]
另外还有一个问题：
3级页面，1级为菜单，2级为表单（表单使用preventdefault进行验证处理），3级为接收表单的提示页面。我在使用用遇到的问题是：当表单提交到3级页面后，此提示页会将其2级页面覆盖掉，然后此时再从1级页面点击该2级页面的链接依然是被覆盖掉的页面（另外在点击3级页面的data-rel="back"按钮也是显示被覆盖的结果）。

**Comment by Rykka** [comment]
呃，还挺麻烦，因为每个页面的元素我用了同样的id。并且页面上的js都没有载入。

**Comment by Rykka** [comment]
是否可以给个 data-load-js 之类的接口，同时加载下js？

**Comment by xingdonghai** [comment]
这种方式也行，但是对于那种必然要在页面中输出的js代码有帮助吗？目前我是修改了mobilebone的代码在加载page的html时同时处理了指定id的script

由iOS专用的myMail发送


2015年3月15日 星期日 +080018:57 发件人 笑可  <notifications@github.com>:

**Comment by zhangxinxu** [comment]
抱歉，此issues有些被埋没了。
上个月某个版本增加了 Mobilebone.evalScript, 设置为true, 可以执行请求页面中的内联script脚本。

还有你提到的表单页面被3级页面是个什么情况，指不能返回吗？

**Comment by xingdonghai** [comment]
我举个例子：
有3个页面：A、B、C，A是一个列表菜单（假如有个“用户注册”）；B是用户注册的表单填写页面，由于一些要求，这里再提交表单的时候不能使用Ajax而是直接post到C页面；那么这个时候C页面既是给予用户反馈成功或失败的提示页面。

问题出在提交之后，无论C页面提示的是什么东西，这个时候我们返回到A页面再次点击这个用户注册，会直接显示之前C页面结果（按理说这里应该要显示B的才对）

不知道我描述的能看明白么，感谢回复。

**Comment by Rykka** [comment]
这里应该是B页面存在一个历史状态的问题。

有没有选项，每次进入这个链接都去这个地址去取相应页面是不是就可以了。

**Comment by zhangxinxu** [comment]
为何点击A页面的用户注册会是C ， 这不科学啊~ 有Demo否？

**Comment by xingdonghai** [comment]
Demo没有了……目前项目已经使用自己写的工具实现了，因为业务单一，我们自己的更合适一些。
