### ISSUE TITLE
onpagefirstinto被重复调用的BUG

### ISSUE THREAD

**Issue by qiuqiu3** [zhangxinxu/mobilebone#83]
我使用到了onpagefirstinto 回调
Mobilebone.onpagefirstinto = function(page) {
	alert('ok');
};
现在有三个页面a.html b.html c.html
a页面有<a href="b.html">b.html</a>
b页面有<a href="c.html">c.html</a>
c页面有<a href="javascript:;" data-rel="back">返回</a>

问题：当有第一次进入a.html时弹出"ok"，点击b.html弹出“ok”，点击c.html弹出“ok”，在c.html页面中点击“返回”又弹出“ok”。

c.html返回到b.html的时候又执行一次onpagefirstinto回调函数，这是不正确的。
后来我看了一下源代码，把271行“var pageid = options.id || pageInto.id;”改成" var pageid = pageInto.id;"暂时解决了，但是不知道会不会对其它的功能有影响。

我曾经在271行下面加入alert(pageid)，运行结果如下：
打开a.html弹出"pageA"
点击b.html弹出“b.html”
点击c.html弹出"c.html

289行有一个判断“if (!store[pageid]) ”
当store等于空时才执行onpagefirstinto回调，但是只有a.html的pageid是正确的，b.html和c.html在store中保存的是[b.html]、[c.html]，而点返回按钮的时候又取的是pageB这个id，store中不存在pageB这个键，所以又执行一次。原因是进入的时候和返回的时候取的pageid不同造成的，希望作者看到后及时修改！

**Comment by zhangxinxu** [comment]
很棒的bug反馈，感谢！！

**Comment by zhangxinxu** [comment]
已更新，popstate的时候，忘记传id了。欢迎继续反馈，共同完善！
