### ISSUE TITLE
AJAX跳转没切换效果

### ISSUE THREAD

**Issue by qiuqiu3** [zhangxinxu/mobilebone#86]
两个页面a.html b.html
当a向b跳转的时候没有切换效果，而是直接显示b页面。b页面返回a的时候也是一样的。
这个BUG需要多次尝试，80%是有切换效果的，只有20%没有切换效果。

**Comment by zhangxinxu** [comment]
你好，可否告知具体设备以及使用场景？有没有url地址可以访问？

**Comment by qiuqiu3** [comment]
你好，这个Bug在电脑的浏览器不存在，手机浏览器随机出现。
我的环境：iPhone 7.1.2 Safari
使用场景：登陆页用Zepto的ajax方法验证。通过后调用Mobilebone.ajax跳转到导航html页。这步有切换效果。导航页有几个a标签链接，点击每个链接跳转下级html。就是这步没有切换效果，还有下级html返回导航页也没有切换效果。
另：登录页引入所有css，每个html加载js用的是seajs的异步加载。和你提供qq那个例子一样。

**Comment by qiuqiu3** [comment]
问题重现例子：Mobilebone-回调测试
页面一-返回 这个操作多做几次就能重现Bug
环境：iPhone 4s Safari

**Comment by zhangxinxu** [comment]
好的，问题收到，正在处理中……

**Comment by zhangxinxu** [comment]
你好，已经更新！感谢反馈，欢迎继续共同建设。

**Comment by qiuqiu3** [comment]
比这前好了一些，但是第一次进入和返回还是没有切换效果，再往后就正常了。

**Comment by qiuqiu3** [comment]
我发现只要把ajax的loading效果去掉就正常了。
