### ISSUE TITLE
data-rel="back"有时候需要点击两次才可以返回

### ISSUE THREAD

**Issue by chfeizy** [zhangxinxu/mobilebone#87]
<a href="javascript:;" class="icon-back" data-rel="back">
href="javascript:;"里如果这样使用
在ajax调用的页面里需要点击两次才可以返回

**Comment by zhangxinxu** [comment]
href="javascript:;" 返回走的是历史记录直接返回。如果没有反应，应该是有连续两次相同的history记录。我处理下~

**Comment by zhangxinxu** [comment]
由于我可以复现的页面，所以我盲改了下，刚刚提交了新版本，如有此问题，还望告知~

**Comment by chfeizy** [comment]
ok测试了给你反馈的

**Comment by qiuqiu3** [comment]
我也遇到过这个问题，每次点两次才返回。

**Comment by chfeizy** [comment]
可以了使用新的js 后

**Comment by zhengjunwei** [comment]
good,加油
