### ISSUE TITLE
ajax请求html页面可否带一些参数？

### ISSUE THREAD

**Issue by qiuqiu3** [zhangxinxu/mobilebone#89]
<a hef="test.html?id=5">带参数</a>
然后我在test.html页面可以获取id这个值？

**Comment by qiuqiu3** [comment]
我现在的做法是在一个共用页面嵌入隐藏的input作为值的交换，然后在a标签中加入click事件给input赋值，另一个页面用js取值。有没有更好的方法呢？

**Comment by zhangxinxu** [comment]
你好，改成动态页面即可。例如：test.php?id=111

**Comment by zhangxinxu** [comment]
又看你这个问题，才明白你的意思。
回调方法中的options参数（纯对象）有个target属性，其值是触发页面过场的那个a元素，你可以直接根据这个a元素得到你想传递的参数。
