### ISSUE TITLE
请问ajax页面跳转后，跳转页面的javascript方法都无效，怎么解决

### ISSUE THREAD

**Issue by fearthedarkness** [zhangxinxu/mobilebone#91]
本身引入了jquery的框架，跳转页面既有页面自动调用的javascript，也有点击按钮调用的javascript，求问怎样才能调用？

**Comment by zhangxinxu** [comment]
你好，这些JS需要在主页面也放置一份。通过<code>.page</code>元素上类似<code>data-callback</code>的回调接口，调用这些JS方法。

**Comment by zhangxinxu** [comment]
你好，抱歉没有及时回复。Mobilebone数个版本前增加了Mobilebone.evalScript, 设置为true, 可以执行请求页面中的内联script脚本。

文档见：http://rawgit.com/zhangxinxu/mobilebone/develop/docs/index.html#&Mobilebone.evalScript.html
