### ISSUE TITLE
你好，我想问下，每次在过场的时候，有没有回调函数

### ISSUE THREAD

**Issue by ghost** [zhangxinxu/mobilebone#97]
我自己在body里面定义了一个<header>，我希望每次页面过场切换的石猴，header里面的内容，可以变化，直接获取页面的title就行了 应为你的data-title是自动变的

**Comment by lishengzxc** [comment]
if (pageInto != null && pageInto.classList) {				
			// for title change
			var title = params_in.title, 
			    header = document.querySelector("h1"), 
			    first_page = document.querySelector("." + this.classPage);	
				
			// do title change	
			//自己的修改
			$("#page-title").text(title);
			if (title) {
				document.title = title;
				if (header) {
					header.innerHTML = title;
					header.title = title;
				}
			} else if (first_page == pageInto && !pageOut && document.title) {
				// set data-title for first visibie page
				pageInto.setAttribute("data-title", document.title);
			}
我反复看了源代码 我修改了一下 不知道可不可以修改，加入你的 master

**Comment by zhangxinxu** [comment]
你好，"#page-title" 增加了学习成本，而且这种id命名风格并不难代表所有个人后团队。使用更有语义的h1标签有什么问题吗？
