### ISSUE TITLE
两次ajax加载后onpagefirstinto callback都会执行两次

### ISSUE THREAD

**Issue by chfeizy** [zhangxinxu/mobilebone#98]
比较紧急希望排查一下

**Comment by chfeizy** [comment]
是data-reload="root" 造成的

**Comment by chfeizy** [comment]
好像也不是 点着点着就 2次了

**Comment by chfeizy** [comment]
应该是 data-reload 的问题

**Comment by chfeizy** [comment]
再就是可否加入销毁pageout

**Comment by chfeizy** [comment]
在chrome device mode 引用了zepto情况下 data-reload使用会加载两次
应该是click和tap 都起作用了

**Comment by zhangxinxu** [comment]
好的，我排查下~

**Comment by zhangxinxu** [comment]
你好，有Demo示意页面吗？

**Comment by chfeizy** [comment]
http://115.29.4.5/mobilebonetest/test/ajax-html/
刚还原效果的过程中发现就是加了iscroll后就出现了页面加载两次

**Comment by chfeizy** [comment]
现在还有几个问题
1.长列表后退退不到原来的位置，列表详细是data-reload="root"
2.pageout销毁，点击多了后加载的page太多，最好可以提供销毁接口减轻压力，back也要做对应处理
3.Mobilebone.captureForm = false;//表单提交没走ajax主要是要做上传图片
在iphone safari form使用了target="iframe id"提交后，第一下点后退不了，应该是记录了历史（chrome没有这个情况）

**Comment by chfeizy** [comment]
4.data-callback data-preventdefault 在sea.js里怎么加载，只能做window.functionname = exports.functionname;全局处理吗

**Comment by chfeizy** [comment]
刚才那个测试页面去掉IScroll页面也会加载两遍在chrome device mode 看network
加上IScroll点到c就加载3次了，callback打印pageID两次

**Comment by zhangxinxu** [comment]
1. 两次加载问题是Mobilebone没有对连续加载mobilebone.js做处理，很好的bug反馈，待会儿提交；
2. 长列表问题我抽空看一下，应该有解决方法；
3. pageout销毁我会考虑，目前确实存在一种类别的页面至少有一个一直存在情况；
4. 表单那个问题我要好好想想……
5. 可以试试在模内部指定Mobilebone.rootTransition为exports~

**Comment by zhangxinxu** [comment]
1. 两次加载问题是Mobilebone没有对连续加载mobilebone.js做处理，很好的bug反馈，待会儿提交；
2. 长列表问题我抽空看一下，应该有解决方法；
3. pageout销毁我会考虑，目前确实存在一种类别的页面至少有一个一直存在情况；
4. 表单那个问题我要好好想想……
5. 可以试试在模内部指定Mobilebone.rootTransition为exports~

**Comment by chfeizy** [comment]
pageout销毁不是说所有的pageout都销毁的，就是提供一个接口，当页面page加载比较多的情况可以选择性的做销毁，减轻客户端浏览器的压力，清理下内存占用

**Comment by chfeizy** [comment]
2.4.3重复加载更加有问题 每次都累加了
