### ISSUE TITLE
Cannot use bower to install mobilebone

### ISSUE THREAD

**Issue by wenzhixin** [zhangxinxu/mobilebone#99]
Hi, when I using `bower install mobilebone`, it occurred an error: `bower ENOTFOUND     Package mobilebone not found`.

**Comment by zhangxinxu** [comment]
好的，感谢反馈！我处理下~

**Comment by zhangxinxu** [comment]
你好，最近github故障比较多，版本下载一直无法访问，需要耐心等待……

**Comment by wenzhixin** [comment]
OK了
